/* Korean Fidget — offline dictionary (no API, bundled)
   Batch 1: ~130 high-frequency words. Keys = Korean word.
   Each entry: { en, zh, ja, es, fr, ru, pt, ar, hi, it }
   Expanding toward 500. */
window.DICT = {
  // ── people / family ──
  "사람": {en:"person", zh:"人", ja:"人", es:"persona", fr:"personne", ru:"человек", pt:"pessoa", ar:"شخص", hi:"व्यक्ति", it:"persona"},
  "사랑": {en:"love", zh:"爱", ja:"愛", es:"amor", fr:"amour", ru:"любовь", pt:"amor", ar:"حب", hi:"प्यार", it:"amore"},
  "친구": {en:"friend", zh:"朋友", ja:"友達", es:"amigo", fr:"ami", ru:"друг", pt:"amigo", ar:"صديق", hi:"दोस्त", it:"amico"},
  "가족": {en:"family", zh:"家人", ja:"家族", es:"familia", fr:"famille", ru:"семья", pt:"família", ar:"عائلة", hi:"परिवार", it:"famiglia"},
  "엄마": {en:"mom", zh:"妈妈", ja:"ママ", es:"mamá", fr:"maman", ru:"мама", pt:"mãe", ar:"أمي", hi:"माँ", it:"mamma"},
  "아빠": {en:"dad", zh:"爸爸", ja:"パパ", es:"papá", fr:"papa", ru:"папа", pt:"pai", ar:"أبي", hi:"पापा", it:"papà"},
  "아기": {en:"baby", zh:"婴儿", ja:"赤ちゃん", es:"bebé", fr:"bébé", ru:"малыш", pt:"bebê", ar:"طفل", hi:"शिशु", it:"bebè"},
  "아이": {en:"child", zh:"孩子", ja:"子供", es:"niño", fr:"enfant", ru:"ребёнок", pt:"criança", ar:"طفل", hi:"बच्चा", it:"bambino"},
  "남자": {en:"man", zh:"男人", ja:"男", es:"hombre", fr:"homme", ru:"мужчина", pt:"homem", ar:"رجل", hi:"आदमी", it:"uomo"},
  "여자": {en:"woman", zh:"女人", ja:"女", es:"mujer", fr:"femme", ru:"женщина", pt:"mulher", ar:"امرأة", hi:"औरत", it:"donna"},
  "이름": {en:"name", zh:"名字", ja:"名前", es:"nombre", fr:"nom", ru:"имя", pt:"nome", ar:"اسم", hi:"नाम", it:"nome"},
  "나": {en:"I / me", zh:"我", ja:"私", es:"yo", fr:"moi", ru:"я", pt:"eu", ar:"أنا", hi:"मैं", it:"io"},
  "너": {en:"you", zh:"你", ja:"あなた", es:"tú", fr:"toi", ru:"ты", pt:"você", ar:"أنت", hi:"तुम", it:"tu"},
  "우리": {en:"we / us", zh:"我们", ja:"私たち", es:"nosotros", fr:"nous", ru:"мы", pt:"nós", ar:"نحن", hi:"हम", it:"noi"},

  // ── nature ──
  "하늘": {en:"sky", zh:"天空", ja:"空", es:"cielo", fr:"ciel", ru:"небо", pt:"céu", ar:"سماء", hi:"आसमान", it:"cielo"},
  "해": {en:"sun", zh:"太阳", ja:"太陽", es:"sol", fr:"soleil", ru:"солнце", pt:"sol", ar:"شمس", hi:"सूरज", it:"sole"},
  "달": {en:"moon / month", zh:"月亮", ja:"月", es:"luna", fr:"lune", ru:"луна", pt:"lua", ar:"قمر", hi:"चाँद", it:"luna"},
  "별": {en:"star", zh:"星星", ja:"星", es:"estrella", fr:"étoile", ru:"звезда", pt:"estrela", ar:"نجمة", hi:"तारा", it:"stella"},
  "산": {en:"mountain", zh:"山", ja:"山", es:"montaña", fr:"montagne", ru:"гора", pt:"montanha", ar:"جبل", hi:"पहाड़", it:"montagna"},
  "강": {en:"river", zh:"河", ja:"川", es:"río", fr:"rivière", ru:"река", pt:"rio", ar:"نهر", hi:"नदी", it:"fiume"},
  "바다": {en:"sea", zh:"海", ja:"海", es:"mar", fr:"mer", ru:"море", pt:"mar", ar:"بحر", hi:"समुद्र", it:"mare"},
  "물": {en:"water", zh:"水", ja:"水", es:"agua", fr:"eau", ru:"вода", pt:"água", ar:"ماء", hi:"पानी", it:"acqua"},
  "불": {en:"fire", zh:"火", ja:"火", es:"fuego", fr:"feu", ru:"огонь", pt:"fogo", ar:"نار", hi:"आग", it:"fuoco"},
  "바람": {en:"wind", zh:"风", ja:"風", es:"viento", fr:"vent", ru:"ветер", pt:"vento", ar:"رياح", hi:"हवा", it:"vento"},
  "비": {en:"rain", zh:"雨", ja:"雨", es:"lluvia", fr:"pluie", ru:"дождь", pt:"chuva", ar:"مطر", hi:"बारिश", it:"pioggia"},
  "눈": {en:"eye / snow", zh:"眼睛／雪", ja:"目／雪", es:"ojo / nieve", fr:"œil / neige", ru:"глаз / снег", pt:"olho / neve", ar:"عين / ثلج", hi:"आँख / बर्फ़", it:"occhio / neve"},
  "나무": {en:"tree", zh:"树", ja:"木", es:"árbol", fr:"arbre", ru:"дерево", pt:"árvore", ar:"شجرة", hi:"पेड़", it:"albero"},
  "꽃": {en:"flower", zh:"花", ja:"花", es:"flor", fr:"fleur", ru:"цветок", pt:"flor", ar:"زهرة", hi:"फूल", it:"fiore"},
  "풀": {en:"grass", zh:"草", ja:"草", es:"hierba", fr:"herbe", ru:"трава", pt:"grama", ar:"عشب", hi:"घास", it:"erba"},
  "돌": {en:"stone", zh:"石头", ja:"石", es:"piedra", fr:"pierre", ru:"камень", pt:"pedra", ar:"حجر", hi:"पत्थर", it:"pietra"},

  // ── animals ──
  "개": {en:"dog", zh:"狗", ja:"犬", es:"perro", fr:"chien", ru:"собака", pt:"cachorro", ar:"كلب", hi:"कुत्ता", it:"cane"},
  "고양이": {en:"cat", zh:"猫", ja:"猫", es:"gato", fr:"chat", ru:"кошка", pt:"gato", ar:"قطة", hi:"बिल्ली", it:"gatto"},
  "새": {en:"bird", zh:"鸟", ja:"鳥", es:"pájaro", fr:"oiseau", ru:"птица", pt:"pássaro", ar:"طائر", hi:"पक्षी", it:"uccello"},
  "소": {en:"cow", zh:"牛", ja:"牛", es:"vaca", fr:"vache", ru:"корова", pt:"vaca", ar:"بقرة", hi:"गाय", it:"mucca"},
  "말": {en:"horse / words", zh:"马／话", ja:"馬／言葉", es:"caballo / palabra", fr:"cheval / parole", ru:"лошадь / слова", pt:"cavalo / fala", ar:"حصان / كلام", hi:"घोड़ा / बात", it:"cavallo / parole"},
  "돼지": {en:"pig", zh:"猪", ja:"豚", es:"cerdo", fr:"cochon", ru:"свинья", pt:"porco", ar:"خنزير", hi:"सूअर", it:"maiale"},
  "닭": {en:"chicken", zh:"鸡", ja:"鶏", es:"pollo", fr:"poulet", ru:"курица", pt:"galinha", ar:"دجاجة", hi:"मुर्गी", it:"pollo"},
  "토끼": {en:"rabbit", zh:"兔子", ja:"うさぎ", es:"conejo", fr:"lapin", ru:"кролик", pt:"coelho", ar:"أرنب", hi:"खरगोश", it:"coniglio"},
  "곰": {en:"bear", zh:"熊", ja:"熊", es:"oso", fr:"ours", ru:"медведь", pt:"urso", ar:"دب", hi:"भालू", it:"orso"},
  "물고기": {en:"fish", zh:"鱼", ja:"魚", es:"pez", fr:"poisson", ru:"рыба", pt:"peixe", ar:"سمكة", hi:"मछली", it:"pesce"},

  // ── food ──
  "밥": {en:"cooked rice / meal", zh:"饭", ja:"ご飯", es:"arroz", fr:"riz", ru:"рис", pt:"arroz", ar:"أرز", hi:"चावल", it:"riso"},
  "국": {en:"soup", zh:"汤", ja:"スープ", es:"sopa", fr:"soupe", ru:"суп", pt:"sopa", ar:"حساء", hi:"सूप", it:"zuppa"},
  "고기": {en:"meat", zh:"肉", ja:"肉", es:"carne", fr:"viande", ru:"мясо", pt:"carne", ar:"لحم", hi:"माँस", it:"carne"},
  "빵": {en:"bread", zh:"面包", ja:"パン", es:"pan", fr:"pain", ru:"хлеб", pt:"pão", ar:"خبز", hi:"रोटी", it:"pane"},
  "우유": {en:"milk", zh:"牛奶", ja:"牛乳", es:"leche", fr:"lait", ru:"молоко", pt:"leite", ar:"حليب", hi:"दूध", it:"latte"},
  "커피": {en:"coffee", zh:"咖啡", ja:"コーヒー", es:"café", fr:"café", ru:"кофе", pt:"café", ar:"قهوة", hi:"कॉफ़ी", it:"caffè"},
  "차": {en:"tea / car", zh:"茶／车", ja:"お茶／車", es:"té / coche", fr:"thé / voiture", ru:"чай / машина", pt:"chá / carro", ar:"شاي / سيارة", hi:"चाय / गाड़ी", it:"tè / auto"},
  "사과": {en:"apple", zh:"苹果", ja:"りんご", es:"manzana", fr:"pomme", ru:"яблоко", pt:"maçã", ar:"تفاحة", hi:"सेब", it:"mela"},
  "포도": {en:"grapes", zh:"葡萄", ja:"ぶどう", es:"uvas", fr:"raisin", ru:"виноград", pt:"uvas", ar:"عنب", hi:"अंगूर", it:"uva"},
  "딸기": {en:"strawberry", zh:"草莓", ja:"いちご", es:"fresa", fr:"fraise", ru:"клубника", pt:"morango", ar:"فراولة", hi:"स्ट्रॉबेरी", it:"fragola"},
  "소금": {en:"salt", zh:"盐", ja:"塩", es:"sal", fr:"sel", ru:"соль", pt:"sal", ar:"ملح", hi:"नमक", it:"sale"},
  "설탕": {en:"sugar", zh:"糖", ja:"砂糖", es:"azúcar", fr:"sucre", ru:"сахар", pt:"açúcar", ar:"سكر", hi:"चीनी", it:"zucchero"},
  "과일": {en:"fruit", zh:"水果", ja:"果物", es:"fruta", fr:"fruit", ru:"фрукт", pt:"fruta", ar:"فاكهة", hi:"फल", it:"frutta"},

  // ── body ──
  "머리": {en:"head / hair", zh:"头", ja:"頭", es:"cabeza", fr:"tête", ru:"голова", pt:"cabeça", ar:"رأس", hi:"सिर", it:"testa"},
  "코": {en:"nose", zh:"鼻子", ja:"鼻", es:"nariz", fr:"nez", ru:"нос", pt:"nariz", ar:"أنف", hi:"नाक", it:"naso"},
  "입": {en:"mouth", zh:"嘴", ja:"口", es:"boca", fr:"bouche", ru:"рот", pt:"boca", ar:"فم", hi:"मुँह", it:"bocca"},
  "귀": {en:"ear", zh:"耳朵", ja:"耳", es:"oreja", fr:"oreille", ru:"ухо", pt:"orelha", ar:"أذن", hi:"कान", it:"orecchio"},
  "손": {en:"hand", zh:"手", ja:"手", es:"mano", fr:"main", ru:"рука", pt:"mão", ar:"يد", hi:"हाथ", it:"mano"},
  "발": {en:"foot", zh:"脚", ja:"足", es:"pie", fr:"pied", ru:"нога", pt:"pé", ar:"قدم", hi:"पैर", it:"piede"},
  "몸": {en:"body", zh:"身体", ja:"体", es:"cuerpo", fr:"corps", ru:"тело", pt:"corpo", ar:"جسم", hi:"शरीर", it:"corpo"},

  // ── home / objects ──
  "집": {en:"house / home", zh:"家", ja:"家", es:"casa", fr:"maison", ru:"дом", pt:"casa", ar:"بيت", hi:"घर", it:"casa"},
  "문": {en:"door", zh:"门", ja:"ドア", es:"puerta", fr:"porte", ru:"дверь", pt:"porta", ar:"باب", hi:"दरवाज़ा", it:"porta"},
  "책": {en:"book", zh:"书", ja:"本", es:"libro", fr:"livre", ru:"книга", pt:"livro", ar:"كتاب", hi:"किताब", it:"libro"},
  "종이": {en:"paper", zh:"纸", ja:"紙", es:"papel", fr:"papier", ru:"бумага", pt:"papel", ar:"ورق", hi:"कागज़", it:"carta"},
  "가방": {en:"bag", zh:"包", ja:"かばん", es:"bolso", fr:"sac", ru:"сумка", pt:"bolsa", ar:"حقيبة", hi:"बैग", it:"borsa"},
  "신발": {en:"shoes", zh:"鞋", ja:"靴", es:"zapatos", fr:"chaussures", ru:"обувь", pt:"sapatos", ar:"حذاء", hi:"जूते", it:"scarpe"},
  "옷": {en:"clothes", zh:"衣服", ja:"服", es:"ropa", fr:"vêtements", ru:"одежда", pt:"roupa", ar:"ملابس", hi:"कपड़े", it:"vestiti"},
  "모자": {en:"hat", zh:"帽子", ja:"帽子", es:"sombrero", fr:"chapeau", ru:"шляпа", pt:"chapéu", ar:"قبعة", hi:"टोपी", it:"cappello"},
  "시계": {en:"clock / watch", zh:"钟表", ja:"時計", es:"reloj", fr:"montre", ru:"часы", pt:"relógio", ar:"ساعة", hi:"घड़ी", it:"orologio"},
  "전화": {en:"phone", zh:"电话", ja:"電話", es:"teléfono", fr:"téléphone", ru:"телефон", pt:"telefone", ar:"هاتف", hi:"फ़ोन", it:"telefono"},
  "의자": {en:"chair", zh:"椅子", ja:"椅子", es:"silla", fr:"chaise", ru:"стул", pt:"cadeira", ar:"كرسي", hi:"कुर्सी", it:"sedia"},
  "돈": {en:"money", zh:"钱", ja:"お金", es:"dinero", fr:"argent", ru:"деньги", pt:"dinheiro", ar:"مال", hi:"पैसा", it:"denaro"},
  "우산": {en:"umbrella", zh:"雨伞", ja:"傘", es:"paraguas", fr:"parapluie", ru:"зонт", pt:"guarda-chuva", ar:"مظلة", hi:"छाता", it:"ombrello"},

  // ── places ──
  "학교": {en:"school", zh:"学校", ja:"学校", es:"escuela", fr:"école", ru:"школа", pt:"escola", ar:"مدرسة", hi:"स्कूल", it:"scuola"},
  "병원": {en:"hospital", zh:"医院", ja:"病院", es:"hospital", fr:"hôpital", ru:"больница", pt:"hospital", ar:"مستشفى", hi:"अस्पताल", it:"ospedale"},
  "가게": {en:"store / shop", zh:"商店", ja:"店", es:"tienda", fr:"magasin", ru:"магазин", pt:"loja", ar:"متجر", hi:"दुकान", it:"negozio"},
  "시장": {en:"market", zh:"市场", ja:"市場", es:"mercado", fr:"marché", ru:"рынок", pt:"mercado", ar:"سوق", hi:"बाज़ार", it:"mercato"},
  "공원": {en:"park", zh:"公园", ja:"公園", es:"parque", fr:"parc", ru:"парк", pt:"parque", ar:"حديقة", hi:"पार्क", it:"parco"},
  "나라": {en:"country", zh:"国家", ja:"国", es:"país", fr:"pays", ru:"страна", pt:"país", ar:"بلد", hi:"देश", it:"paese"},
  "도시": {en:"city", zh:"城市", ja:"都市", es:"ciudad", fr:"ville", ru:"город", pt:"cidade", ar:"مدينة", hi:"शहर", it:"città"},
  "길": {en:"road / street", zh:"路", ja:"道", es:"calle", fr:"rue", ru:"дорога", pt:"rua", ar:"طريق", hi:"सड़क", it:"strada"},
  "방": {en:"room", zh:"房间", ja:"部屋", es:"habitación", fr:"chambre", ru:"комната", pt:"quarto", ar:"غرفة", hi:"कमरा", it:"stanza"},

  // ── time ──
  "오늘": {en:"today", zh:"今天", ja:"今日", es:"hoy", fr:"aujourd'hui", ru:"сегодня", pt:"hoje", ar:"اليوم", hi:"आज", it:"oggi"},
  "내일": {en:"tomorrow", zh:"明天", ja:"明日", es:"mañana", fr:"demain", ru:"завтра", pt:"amanhã", ar:"غدًا", hi:"कल", it:"domani"},
  "어제": {en:"yesterday", zh:"昨天", ja:"昨日", es:"ayer", fr:"hier", ru:"вчера", pt:"ontem", ar:"أمس", hi:"कल (बीता)", it:"ieri"},
  "아침": {en:"morning", zh:"早上", ja:"朝", es:"mañana", fr:"matin", ru:"утро", pt:"manhã", ar:"صباح", hi:"सुबह", it:"mattina"},
  "저녁": {en:"evening", zh:"晚上", ja:"夕方", es:"tarde / noche", fr:"soir", ru:"вечер", pt:"noite", ar:"مساء", hi:"शाम", it:"sera"},
  "밤": {en:"night", zh:"夜晚", ja:"夜", es:"noche", fr:"nuit", ru:"ночь", pt:"noite", ar:"ليل", hi:"रात", it:"notte"},
  "시간": {en:"time / hour", zh:"时间", ja:"時間", es:"tiempo / hora", fr:"temps / heure", ru:"время / час", pt:"tempo / hora", ar:"وقت / ساعة", hi:"समय / घंटा", it:"tempo / ora"},
  "지금": {en:"now", zh:"现在", ja:"今", es:"ahora", fr:"maintenant", ru:"сейчас", pt:"agora", ar:"الآن", hi:"अभी", it:"adesso"},

  // ── colors ──
  "색": {en:"color", zh:"颜色", ja:"色", es:"color", fr:"couleur", ru:"цвет", pt:"cor", ar:"لون", hi:"रंग", it:"colore"},
  "빨강": {en:"red", zh:"红色", ja:"赤", es:"rojo", fr:"rouge", ru:"красный", pt:"vermelho", ar:"أحمر", hi:"लाल", it:"rosso"},
  "파랑": {en:"blue", zh:"蓝色", ja:"青", es:"azul", fr:"bleu", ru:"синий", pt:"azul", ar:"أزرق", hi:"नीला", it:"blu"},
  "노랑": {en:"yellow", zh:"黄色", ja:"黄", es:"amarillo", fr:"jaune", ru:"жёлтый", pt:"amarelo", ar:"أصفر", hi:"पीला", it:"giallo"},
  "초록": {en:"green", zh:"绿色", ja:"緑", es:"verde", fr:"vert", ru:"зелёный", pt:"verde", ar:"أخضر", hi:"हरा", it:"verde"},

  // ── numbers (native Korean) ──
  "하나": {en:"one", zh:"一", ja:"一つ", es:"uno", fr:"un", ru:"один", pt:"um", ar:"واحد", hi:"एक", it:"uno"},
  "둘": {en:"two", zh:"二", ja:"二つ", es:"dos", fr:"deux", ru:"два", pt:"dois", ar:"اثنان", hi:"दो", it:"due"},
  "셋": {en:"three", zh:"三", ja:"三つ", es:"tres", fr:"trois", ru:"три", pt:"três", ar:"ثلاثة", hi:"तीन", it:"tre"},
  "넷": {en:"four", zh:"四", ja:"四つ", es:"cuatro", fr:"quatre", ru:"четыре", pt:"quatro", ar:"أربعة", hi:"चार", it:"quattro"},
  "다섯": {en:"five", zh:"五", ja:"五つ", es:"cinco", fr:"cinq", ru:"пять", pt:"cinco", ar:"خمسة", hi:"पाँच", it:"cinque"},
  "여섯": {en:"six", zh:"六", ja:"六つ", es:"seis", fr:"six", ru:"шесть", pt:"seis", ar:"ستة", hi:"छह", it:"sei"},
  "일곱": {en:"seven", zh:"七", ja:"七つ", es:"siete", fr:"sept", ru:"семь", pt:"sete", ar:"سبعة", hi:"सात", it:"sette"},
  "여덟": {en:"eight", zh:"八", ja:"八つ", es:"ocho", fr:"huit", ru:"восемь", pt:"oito", ar:"ثمانية", hi:"आठ", it:"otto"},
  "아홉": {en:"nine", zh:"九", ja:"九つ", es:"nueve", fr:"neuf", ru:"девять", pt:"nove", ar:"تسعة", hi:"नौ", it:"nove"},
  "열": {en:"ten", zh:"十", ja:"十", es:"diez", fr:"dix", ru:"десять", pt:"dez", ar:"عشرة", hi:"दस", it:"dieci"},

  // ── common verbs (dictionary form) ──
  "가다": {en:"to go", zh:"去", ja:"行く", es:"ir", fr:"aller", ru:"идти", pt:"ir", ar:"يذهب", hi:"जाना", it:"andare"},
  "오다": {en:"to come", zh:"来", ja:"来る", es:"venir", fr:"venir", ru:"приходить", pt:"vir", ar:"يأتي", hi:"आना", it:"venire"},
  "먹다": {en:"to eat", zh:"吃", ja:"食べる", es:"comer", fr:"manger", ru:"есть", pt:"comer", ar:"يأكل", hi:"खाना", it:"mangiare"},
  "자다": {en:"to sleep", zh:"睡觉", ja:"寝る", es:"dormir", fr:"dormir", ru:"спать", pt:"dormir", ar:"ينام", hi:"सोना", it:"dormire"},
  "보다": {en:"to see", zh:"看", ja:"見る", es:"ver", fr:"voir", ru:"видеть", pt:"ver", ar:"يرى", hi:"देखना", it:"vedere"},
  "하다": {en:"to do", zh:"做", ja:"する", es:"hacer", fr:"faire", ru:"делать", pt:"fazer", ar:"يفعل", hi:"करना", it:"fare"},
  "사다": {en:"to buy", zh:"买", ja:"買う", es:"comprar", fr:"acheter", ru:"покупать", pt:"comprar", ar:"يشتري", hi:"खरीदना", it:"comprare"},
  "읽다": {en:"to read", zh:"读", ja:"読む", es:"leer", fr:"lire", ru:"читать", pt:"ler", ar:"يقرأ", hi:"पढ़ना", it:"leggere"},
  "놀다": {en:"to play", zh:"玩", ja:"遊ぶ", es:"jugar", fr:"jouer", ru:"играть", pt:"brincar", ar:"يلعب", hi:"खेलना", it:"giocare"},
  "웃다": {en:"to laugh", zh:"笑", ja:"笑う", es:"reír", fr:"rire", ru:"смеяться", pt:"rir", ar:"يضحك", hi:"हँसना", it:"ridere"},
  "울다": {en:"to cry", zh:"哭", ja:"泣く", es:"llorar", fr:"pleurer", ru:"плакать", pt:"chorar", ar:"يبكي", hi:"रोना", it:"piangere"},
  "걷다": {en:"to walk", zh:"走", ja:"歩く", es:"caminar", fr:"marcher", ru:"ходить", pt:"caminhar", ar:"يمشي", hi:"चलना", it:"camminare"},
  "뛰다": {en:"to run", zh:"跑", ja:"走る", es:"correr", fr:"courir", ru:"бегать", pt:"correr", ar:"يركض", hi:"दौड़ना", it:"correre"},

  // ── common adjectives (dictionary form) ──
  "크다": {en:"to be big", zh:"大", ja:"大きい", es:"grande", fr:"grand", ru:"большой", pt:"grande", ar:"كبير", hi:"बड़ा", it:"grande"},
  "작다": {en:"to be small", zh:"小", ja:"小さい", es:"pequeño", fr:"petit", ru:"маленький", pt:"pequeno", ar:"صغير", hi:"छोटा", it:"piccolo"},
  "좋다": {en:"to be good", zh:"好", ja:"良い", es:"bueno", fr:"bon", ru:"хороший", pt:"bom", ar:"جيد", hi:"अच्छा", it:"buono"},
  "많다": {en:"to be many", zh:"多", ja:"多い", es:"mucho", fr:"beaucoup", ru:"много", pt:"muito", ar:"كثير", hi:"बहुत", it:"molto"},
  "춥다": {en:"to be cold", zh:"冷", ja:"寒い", es:"frío", fr:"froid", ru:"холодно", pt:"frio", ar:"بارد", hi:"ठंडा", it:"freddo"},
  "덥다": {en:"to be hot", zh:"热", ja:"暑い", es:"caluroso", fr:"chaud", ru:"жарко", pt:"quente", ar:"حار", hi:"गरम", it:"caldo"},

  // ── batch 2 ──
  // people
  "할머니": {en:"grandmother", zh:"奶奶", ja:"おばあさん", es:"abuela", fr:"grand-mère", ru:"бабушка", pt:"avó", ar:"جدة", hi:"दादी", it:"nonna"},
  "할아버지": {en:"grandfather", zh:"爷爷", ja:"おじいさん", es:"abuelo", fr:"grand-père", ru:"дедушка", pt:"avô", ar:"جد", hi:"दादा", it:"nonno"},
  "아들": {en:"son", zh:"儿子", ja:"息子", es:"hijo", fr:"fils", ru:"сын", pt:"filho", ar:"ابن", hi:"बेटा", it:"figlio"},
  "딸": {en:"daughter", zh:"女儿", ja:"娘", es:"hija", fr:"fille", ru:"дочь", pt:"filha", ar:"ابنة", hi:"बेटी", it:"figlia"},
  "형": {en:"older brother (for males)", zh:"哥哥", ja:"兄", es:"hermano mayor", fr:"grand frère", ru:"старший брат", pt:"irmão mais velho", ar:"أخ أكبر", hi:"बड़ा भाई", it:"fratello maggiore"},
  "누나": {en:"older sister (for males)", zh:"姐姐", ja:"姉", es:"hermana mayor", fr:"grande sœur", ru:"старшая сестра", pt:"irmã mais velha", ar:"أخت كبرى", hi:"बड़ी बहन", it:"sorella maggiore"},
  "동생": {en:"younger sibling", zh:"弟弟妹妹", ja:"弟・妹", es:"hermano menor", fr:"cadet", ru:"младший", pt:"irmão mais novo", ar:"أخ أصغر", hi:"छोटा भाई/बहन", it:"fratello minore"},
  "의사": {en:"doctor", zh:"医生", ja:"医者", es:"médico", fr:"médecin", ru:"врач", pt:"médico", ar:"طبيب", hi:"डॉक्टर", it:"medico"},
  "간호사": {en:"nurse", zh:"护士", ja:"看護師", es:"enfermero", fr:"infirmier", ru:"медсестра", pt:"enfermeiro", ar:"ممرض", hi:"नर्स", it:"infermiere"},
  "경찰": {en:"police", zh:"警察", ja:"警察", es:"policía", fr:"police", ru:"полиция", pt:"polícia", ar:"شرطة", hi:"पुलिस", it:"polizia"},
  "학생": {en:"student", zh:"学生", ja:"学生", es:"estudiante", fr:"étudiant", ru:"студент", pt:"estudante", ar:"طالب", hi:"छात्र", it:"studente"},
  "선생님": {en:"teacher", zh:"老师", ja:"先生", es:"profesor", fr:"professeur", ru:"учитель", pt:"professor", ar:"معلم", hi:"शिक्षक", it:"insegnante"},
  "가수": {en:"singer", zh:"歌手", ja:"歌手", es:"cantante", fr:"chanteur", ru:"певец", pt:"cantor", ar:"مغني", hi:"गायक", it:"cantante"},
  "왕": {en:"king", zh:"国王", ja:"王", es:"rey", fr:"roi", ru:"король", pt:"rei", ar:"ملك", hi:"राजा", it:"re"},

  // animals
  "강아지": {en:"puppy", zh:"小狗", ja:"子犬", es:"cachorro", fr:"chiot", ru:"щенок", pt:"filhote", ar:"جرو", hi:"पिल्ला", it:"cucciolo"},
  "병아리": {en:"chick", zh:"小鸡", ja:"ひよこ", es:"pollito", fr:"poussin", ru:"цыплёнок", pt:"pintinho", ar:"كتكوت", hi:"चूज़ा", it:"pulcino"},
  "오리": {en:"duck", zh:"鸭子", ja:"あひる", es:"pato", fr:"canard", ru:"утка", pt:"pato", ar:"بطة", hi:"बत्तख़", it:"anatra"},
  "사슴": {en:"deer", zh:"鹿", ja:"鹿", es:"ciervo", fr:"cerf", ru:"олень", pt:"veado", ar:"غزال", hi:"हिरण", it:"cervo"},
  "여우": {en:"fox", zh:"狐狸", ja:"きつね", es:"zorro", fr:"renard", ru:"лиса", pt:"raposa", ar:"ثعلب", hi:"लोमड़ी", it:"volpe"},
  "늑대": {en:"wolf", zh:"狼", ja:"狼", es:"lobo", fr:"loup", ru:"волк", pt:"lobo", ar:"ذئب", hi:"भेड़िया", it:"lupo"},
  "코끼리": {en:"elephant", zh:"大象", ja:"象", es:"elefante", fr:"éléphant", ru:"слон", pt:"elefante", ar:"فيل", hi:"हाथी", it:"elefante"},
  "기린": {en:"giraffe", zh:"长颈鹿", ja:"キリン", es:"jirafa", fr:"girafe", ru:"жираф", pt:"girafa", ar:"زرافة", hi:"जिराफ़", it:"giraffa"},
  "원숭이": {en:"monkey", zh:"猴子", ja:"猿", es:"mono", fr:"singe", ru:"обезьяна", pt:"macaco", ar:"قرد", hi:"बंदर", it:"scimmia"},
  "거북이": {en:"turtle", zh:"乌龟", ja:"亀", es:"tortuga", fr:"tortue", ru:"черепаха", pt:"tartaruga", ar:"سلحفاة", hi:"कछुआ", it:"tartaruga"},
  "개구리": {en:"frog", zh:"青蛙", ja:"カエル", es:"rana", fr:"grenouille", ru:"лягушка", pt:"sapo", ar:"ضفدع", hi:"मेंढक", it:"rana"},
  "나비": {en:"butterfly", zh:"蝴蝶", ja:"蝶", es:"mariposa", fr:"papillon", ru:"бабочка", pt:"borboleta", ar:"فراشة", hi:"तितली", it:"farfalla"},
  "벌": {en:"bee", zh:"蜜蜂", ja:"蜂", es:"abeja", fr:"abeille", ru:"пчела", pt:"abelha", ar:"نحلة", hi:"मधुमक्खी", it:"ape"},
  "개미": {en:"ant", zh:"蚂蚁", ja:"蟻", es:"hormiga", fr:"fourmi", ru:"муравей", pt:"formiga", ar:"نملة", hi:"चींटी", it:"formica"},
  "거미": {en:"spider", zh:"蜘蛛", ja:"蜘蛛", es:"araña", fr:"araignée", ru:"паук", pt:"aranha", ar:"عنكبوت", hi:"मकड़ी", it:"ragno"},
  "고래": {en:"whale", zh:"鲸鱼", ja:"鯨", es:"ballena", fr:"baleine", ru:"кит", pt:"baleia", ar:"حوت", hi:"व्हेल", it:"balena"},
  "상어": {en:"shark", zh:"鲨鱼", ja:"サメ", es:"tiburón", fr:"requin", ru:"акула", pt:"tubarão", ar:"قرش", hi:"शार्क", it:"squalo"},
  "양": {en:"sheep", zh:"羊", ja:"羊", es:"oveja", fr:"mouton", ru:"овца", pt:"ovelha", ar:"خروف", hi:"भेड़", it:"pecora"},
  "쥐": {en:"mouse / rat", zh:"老鼠", ja:"ねずみ", es:"ratón", fr:"souris", ru:"мышь", pt:"rato", ar:"فأر", hi:"चूहा", it:"topo"},
  "뱀": {en:"snake", zh:"蛇", ja:"蛇", es:"serpiente", fr:"serpent", ru:"змея", pt:"cobra", ar:"ثعبان", hi:"साँप", it:"serpente"},

  // food & drink
  "계란": {en:"egg", zh:"鸡蛋", ja:"卵", es:"huevo", fr:"œuf", ru:"яйцо", pt:"ovo", ar:"بيضة", hi:"अंडा", it:"uovo"},
  "생선": {en:"fish (food)", zh:"鱼", ja:"魚", es:"pescado", fr:"poisson", ru:"рыба", pt:"peixe", ar:"سمك", hi:"मछली", it:"pesce"},
  "새우": {en:"shrimp", zh:"虾", ja:"えび", es:"camarón", fr:"crevette", ru:"креветка", pt:"camarão", ar:"جمبري", hi:"झींगा", it:"gambero"},
  "감자": {en:"potato", zh:"土豆", ja:"じゃがいも", es:"papa", fr:"pomme de terre", ru:"картофель", pt:"batata", ar:"بطاطس", hi:"आलू", it:"patata"},
  "당근": {en:"carrot", zh:"胡萝卜", ja:"にんじん", es:"zanahoria", fr:"carotte", ru:"морковь", pt:"cenoura", ar:"جزر", hi:"गाजर", it:"carota"},
  "오이": {en:"cucumber", zh:"黄瓜", ja:"きゅうり", es:"pepino", fr:"concombre", ru:"огурец", pt:"pepino", ar:"خيار", hi:"खीरा", it:"cetriolo"},
  "양파": {en:"onion", zh:"洋葱", ja:"玉ねぎ", es:"cebolla", fr:"oignon", ru:"лук", pt:"cebola", ar:"بصل", hi:"प्याज़", it:"cipolla"},
  "마늘": {en:"garlic", zh:"大蒜", ja:"にんにく", es:"ajo", fr:"ail", ru:"чеснок", pt:"alho", ar:"ثوم", hi:"लहसुन", it:"aglio"},
  "버섯": {en:"mushroom", zh:"蘑菇", ja:"きのこ", es:"champiñón", fr:"champignon", ru:"гриб", pt:"cogumelo", ar:"فطر", hi:"मशरूम", it:"fungo"},
  "두부": {en:"tofu", zh:"豆腐", ja:"豆腐", es:"tofu", fr:"tofu", ru:"тофу", pt:"tofu", ar:"توفو", hi:"टोफ़ू", it:"tofu"},
  "콩": {en:"bean", zh:"豆", ja:"豆", es:"frijol", fr:"haricot", ru:"боб", pt:"feijão", ar:"فاصوليا", hi:"सेम", it:"fagiolo"},
  "바나나": {en:"banana", zh:"香蕉", ja:"バナナ", es:"plátano", fr:"banane", ru:"банан", pt:"banana", ar:"موز", hi:"केला", it:"banana"},
  "오렌지": {en:"orange", zh:"橙子", ja:"オレンジ", es:"naranja", fr:"orange", ru:"апельсин", pt:"laranja", ar:"برتقال", hi:"संतरा", it:"arancia"},
  "레몬": {en:"lemon", zh:"柠檬", ja:"レモン", es:"limón", fr:"citron", ru:"лимон", pt:"limão", ar:"ليمون", hi:"नींबू", it:"limone"},
  "복숭아": {en:"peach", zh:"桃子", ja:"桃", es:"durazno", fr:"pêche", ru:"персик", pt:"pêssego", ar:"خوخ", hi:"आड़ू", it:"pesca"},
  "수박": {en:"watermelon", zh:"西瓜", ja:"スイカ", es:"sandía", fr:"pastèque", ru:"арбуз", pt:"melancia", ar:"بطيخ", hi:"तरबूज़", it:"anguria"},
  "라면": {en:"ramen", zh:"拉面", ja:"ラーメン", es:"ramen", fr:"ramen", ru:"рамён", pt:"lámen", ar:"رامن", hi:"रामन", it:"ramen"},
  "국수": {en:"noodles", zh:"面条", ja:"麺", es:"fideos", fr:"nouilles", ru:"лапша", pt:"macarrão", ar:"نودلز", hi:"नूडल्स", it:"noodles"},
  "떡": {en:"rice cake", zh:"年糕", ja:"餅", es:"pastel de arroz", fr:"gâteau de riz", ru:"рисовый пирог", pt:"bolo de arroz", ar:"كعكة أرز", hi:"चावल केक", it:"dolce di riso"},
  "과자": {en:"snack / cookie", zh:"饼干", ja:"お菓子", es:"galleta", fr:"biscuit", ru:"печенье", pt:"biscoito", ar:"بسكويت", hi:"बिस्कुट", it:"biscotto"},
  "사탕": {en:"candy", zh:"糖果", ja:"あめ", es:"caramelo", fr:"bonbon", ru:"конфета", pt:"bala", ar:"حلوى", hi:"कैंडी", it:"caramella"},
  "초콜릿": {en:"chocolate", zh:"巧克力", ja:"チョコレート", es:"chocolate", fr:"chocolat", ru:"шоколад", pt:"chocolate", ar:"شوكولاتة", hi:"चॉकलेट", it:"cioccolato"},
  "치즈": {en:"cheese", zh:"奶酪", ja:"チーズ", es:"queso", fr:"fromage", ru:"сыр", pt:"queijo", ar:"جبن", hi:"पनीर", it:"formaggio"},
  "꿀": {en:"honey", zh:"蜂蜜", ja:"はちみつ", es:"miel", fr:"miel", ru:"мёд", pt:"mel", ar:"عسل", hi:"शहद", it:"miele"},
  "주스": {en:"juice", zh:"果汁", ja:"ジュース", es:"jugo", fr:"jus", ru:"сок", pt:"suco", ar:"عصير", hi:"जूस", it:"succo"},

  // body
  "얼굴": {en:"face", zh:"脸", ja:"顔", es:"cara", fr:"visage", ru:"лицо", pt:"rosto", ar:"وجه", hi:"चेहरा", it:"faccia"},
  "목": {en:"neck / throat", zh:"脖子", ja:"首", es:"cuello", fr:"cou", ru:"шея", pt:"pescoço", ar:"رقبة", hi:"गर्दन", it:"collo"},
  "어깨": {en:"shoulder", zh:"肩膀", ja:"肩", es:"hombro", fr:"épaule", ru:"плечо", pt:"ombro", ar:"كتف", hi:"कंधा", it:"spalla"},
  "가슴": {en:"chest", zh:"胸", ja:"胸", es:"pecho", fr:"poitrine", ru:"грудь", pt:"peito", ar:"صدر", hi:"छाती", it:"petto"},
  "무릎": {en:"knee", zh:"膝盖", ja:"ひざ", es:"rodilla", fr:"genou", ru:"колено", pt:"joelho", ar:"ركبة", hi:"घुटना", it:"ginocchio"},
  "손가락": {en:"finger", zh:"手指", ja:"指", es:"dedo", fr:"doigt", ru:"палец", pt:"dedo", ar:"إصبع", hi:"उंगली", it:"dito"},
  "혀": {en:"tongue", zh:"舌头", ja:"舌", es:"lengua", fr:"langue", ru:"язык", pt:"língua", ar:"لسان", hi:"जीभ", it:"lingua"},
  "피": {en:"blood", zh:"血", ja:"血", es:"sangre", fr:"sang", ru:"кровь", pt:"sangue", ar:"دم", hi:"ख़ून", it:"sangue"},
  "뼈": {en:"bone", zh:"骨头", ja:"骨", es:"hueso", fr:"os", ru:"кость", pt:"osso", ar:"عظم", hi:"हड्डी", it:"osso"},
  "심장": {en:"heart (organ)", zh:"心脏", ja:"心臓", es:"corazón", fr:"cœur", ru:"сердце", pt:"coração", ar:"قلب", hi:"दिल", it:"cuore"},
  "배": {en:"belly / ship / pear", zh:"肚子／船／梨", ja:"お腹／船／梨", es:"barriga / barco / pera", fr:"ventre / bateau / poire", ru:"живот / корабль / груша", pt:"barriga / navio / pera", ar:"بطن / سفينة / كمثرى", hi:"पेट / जहाज़ / नाशपाती", it:"pancia / nave / pera"},

  // clothes & objects
  "바지": {en:"pants", zh:"裤子", ja:"ズボン", es:"pantalones", fr:"pantalon", ru:"брюки", pt:"calça", ar:"بنطال", hi:"पैंट", it:"pantaloni"},
  "치마": {en:"skirt", zh:"裙子", ja:"スカート", es:"falda", fr:"jupe", ru:"юбка", pt:"saia", ar:"تنورة", hi:"स्कर्ट", it:"gonna"},
  "양말": {en:"socks", zh:"袜子", ja:"靴下", es:"calcetines", fr:"chaussettes", ru:"носки", pt:"meias", ar:"جوارب", hi:"मोज़े", it:"calze"},
  "장갑": {en:"gloves", zh:"手套", ja:"手袋", es:"guantes", fr:"gants", ru:"перчатки", pt:"luvas", ar:"قفازات", hi:"दस्ताने", it:"guanti"},
  "안경": {en:"glasses", zh:"眼镜", ja:"眼鏡", es:"gafas", fr:"lunettes", ru:"очки", pt:"óculos", ar:"نظارة", hi:"चश्मा", it:"occhiali"},
  "반지": {en:"ring", zh:"戒指", ja:"指輪", es:"anillo", fr:"bague", ru:"кольцо", pt:"anel", ar:"خاتم", hi:"अंगूठी", it:"anello"},
  "수건": {en:"towel", zh:"毛巾", ja:"タオル", es:"toalla", fr:"serviette", ru:"полотенце", pt:"toalha", ar:"منشفة", hi:"तौलिया", it:"asciugamano"},
  "숟가락": {en:"spoon", zh:"勺子", ja:"スプーン", es:"cuchara", fr:"cuillère", ru:"ложка", pt:"colher", ar:"ملعقة", hi:"चम्मच", it:"cucchiaio"},
  "젓가락": {en:"chopsticks", zh:"筷子", ja:"箸", es:"palillos", fr:"baguettes", ru:"палочки", pt:"pauzinhos", ar:"عيدان", hi:"चॉपस्टिक", it:"bacchette"},
  "그릇": {en:"bowl", zh:"碗", ja:"器", es:"tazón", fr:"bol", ru:"миска", pt:"tigela", ar:"وعاء", hi:"कटोरा", it:"ciotola"},
  "접시": {en:"plate", zh:"盘子", ja:"皿", es:"plato", fr:"assiette", ru:"тарелка", pt:"prato", ar:"طبق", hi:"प्लेट", it:"piatto"},
  "컵": {en:"cup", zh:"杯子", ja:"コップ", es:"taza", fr:"tasse", ru:"чашка", pt:"copo", ar:"كوب", hi:"कप", it:"tazza"},
  "칼": {en:"knife", zh:"刀", ja:"ナイフ", es:"cuchillo", fr:"couteau", ru:"нож", pt:"faca", ar:"سكين", hi:"चाकू", it:"coltello"},
  "가위": {en:"scissors", zh:"剪刀", ja:"はさみ", es:"tijeras", fr:"ciseaux", ru:"ножницы", pt:"tesoura", ar:"مقص", hi:"कैंची", it:"forbici"},
  "비누": {en:"soap", zh:"肥皂", ja:"石けん", es:"jabón", fr:"savon", ru:"мыло", pt:"sabonete", ar:"صابون", hi:"साबुन", it:"sapone"},
  "베개": {en:"pillow", zh:"枕头", ja:"枕", es:"almohada", fr:"oreiller", ru:"подушка", pt:"travesseiro", ar:"وسادة", hi:"तकिया", it:"cuscino"},
  "냉장고": {en:"refrigerator", zh:"冰箱", ja:"冷蔵庫", es:"refrigerador", fr:"réfrigérateur", ru:"холодильник", pt:"geladeira", ar:"ثلاجة", hi:"फ्रिज", it:"frigorifero"},
  "상자": {en:"box", zh:"箱子", ja:"箱", es:"caja", fr:"boîte", ru:"коробка", pt:"caixa", ar:"صندوق", hi:"डिब्बा", it:"scatola"},
  "편지": {en:"letter (mail)", zh:"信", ja:"手紙", es:"carta", fr:"lettre", ru:"письмо", pt:"carta", ar:"رسالة", hi:"पत्र", it:"lettera"},
  "지도": {en:"map", zh:"地图", ja:"地図", es:"mapa", fr:"carte", ru:"карта", pt:"mapa", ar:"خريطة", hi:"नक्शा", it:"mappa"},
  "사진": {en:"photo", zh:"照片", ja:"写真", es:"foto", fr:"photo", ru:"фото", pt:"foto", ar:"صورة", hi:"तस्वीर", it:"foto"},
  "그림": {en:"picture / drawing", zh:"画", ja:"絵", es:"dibujo", fr:"dessin", ru:"рисунок", pt:"desenho", ar:"رسم", hi:"चित्र", it:"disegno"},
  "공": {en:"ball", zh:"球", ja:"ボール", es:"pelota", fr:"balle", ru:"мяч", pt:"bola", ar:"كرة", hi:"गेंद", it:"palla"},
  "인형": {en:"doll", zh:"娃娃", ja:"人形", es:"muñeca", fr:"poupée", ru:"кукла", pt:"boneca", ar:"دمية", hi:"गुड़िया", it:"bambola"},

  // vehicles
  "버스": {en:"bus", zh:"公交车", ja:"バス", es:"autobús", fr:"bus", ru:"автобус", pt:"ônibus", ar:"حافلة", hi:"बस", it:"autobus"},
  "기차": {en:"train", zh:"火车", ja:"汽車", es:"tren", fr:"train", ru:"поезд", pt:"trem", ar:"قطار", hi:"रेलगाड़ी", it:"treno"},
  "자전거": {en:"bicycle", zh:"自行车", ja:"自転車", es:"bicicleta", fr:"vélo", ru:"велосипед", pt:"bicicleta", ar:"دراجة", hi:"साइकिल", it:"bicicletta"},
  "비행기": {en:"airplane", zh:"飞机", ja:"飛行機", es:"avión", fr:"avion", ru:"самолёт", pt:"avião", ar:"طائرة", hi:"हवाई जहाज़", it:"aereo"},
  "택시": {en:"taxi", zh:"出租车", ja:"タクシー", es:"taxi", fr:"taxi", ru:"такси", pt:"táxi", ar:"تاكسي", hi:"टैक्सी", it:"taxi"},

  // nature & weather
  "구름": {en:"cloud", zh:"云", ja:"雲", es:"nube", fr:"nuage", ru:"облако", pt:"nuvem", ar:"سحابة", hi:"बादल", it:"nuvola"},
  "무지개": {en:"rainbow", zh:"彩虹", ja:"虹", es:"arcoíris", fr:"arc-en-ciel", ru:"радуга", pt:"arco-íris", ar:"قوس قزح", hi:"इंद्रधनुष", it:"arcobaleno"},
  "얼음": {en:"ice", zh:"冰", ja:"氷", es:"hielo", fr:"glace", ru:"лёд", pt:"gelo", ar:"ثلج", hi:"बर्फ़", it:"ghiaccio"},
  "빛": {en:"light", zh:"光", ja:"光", es:"luz", fr:"lumière", ru:"свет", pt:"luz", ar:"ضوء", hi:"रोशनी", it:"luce"},
  "소리": {en:"sound", zh:"声音", ja:"音", es:"sonido", fr:"son", ru:"звук", pt:"som", ar:"صوت", hi:"आवाज़", it:"suono"},
  "공기": {en:"air", zh:"空气", ja:"空気", es:"aire", fr:"air", ru:"воздух", pt:"ar", ar:"هواء", hi:"हवा", it:"aria"},
  "섬": {en:"island", zh:"岛", ja:"島", es:"isla", fr:"île", ru:"остров", pt:"ilha", ar:"جزيرة", hi:"द्वीप", it:"isola"},
  "호수": {en:"lake", zh:"湖", ja:"湖", es:"lago", fr:"lac", ru:"озеро", pt:"lago", ar:"بحيرة", hi:"झील", it:"lago"},
  "숲": {en:"forest", zh:"森林", ja:"森", es:"bosque", fr:"forêt", ru:"лес", pt:"floresta", ar:"غابة", hi:"जंगल", it:"foresta"},

  // seasons & time
  "봄": {en:"spring", zh:"春天", ja:"春", es:"primavera", fr:"printemps", ru:"весна", pt:"primavera", ar:"ربيع", hi:"वसंत", it:"primavera"},
  "여름": {en:"summer", zh:"夏天", ja:"夏", es:"verano", fr:"été", ru:"лето", pt:"verão", ar:"صيف", hi:"गर्मी", it:"estate"},
  "가을": {en:"autumn", zh:"秋天", ja:"秋", es:"otoño", fr:"automne", ru:"осень", pt:"outono", ar:"خريف", hi:"पतझड़", it:"autunno"},
  "겨울": {en:"winter", zh:"冬天", ja:"冬", es:"invierno", fr:"hiver", ru:"зима", pt:"inverno", ar:"شتاء", hi:"सर्दी", it:"inverno"},
  "주말": {en:"weekend", zh:"周末", ja:"週末", es:"fin de semana", fr:"week-end", ru:"выходные", pt:"fim de semana", ar:"عطلة نهاية الأسبوع", hi:"सप्ताहांत", it:"fine settimana"},
  "생일": {en:"birthday", zh:"生日", ja:"誕生日", es:"cumpleaños", fr:"anniversaire", ru:"день рождения", pt:"aniversário", ar:"عيد ميلاد", hi:"जन्मदिन", it:"compleanno"},

  // common verbs & adjectives
  "마시다": {en:"to drink", zh:"喝", ja:"飲む", es:"beber", fr:"boire", ru:"пить", pt:"beber", ar:"يشرب", hi:"पीना", it:"bere"},
  "만들다": {en:"to make", zh:"做", ja:"作る", es:"hacer", fr:"fabriquer", ru:"делать", pt:"fazer", ar:"يصنع", hi:"बनाना", it:"creare"},
  "주다": {en:"to give", zh:"给", ja:"あげる", es:"dar", fr:"donner", ru:"давать", pt:"dar", ar:"يعطي", hi:"देना", it:"dare"},
  "받다": {en:"to receive", zh:"收", ja:"受け取る", es:"recibir", fr:"recevoir", ru:"получать", pt:"receber", ar:"يستلم", hi:"पाना", it:"ricevere"},
  "앉다": {en:"to sit", zh:"坐", ja:"座る", es:"sentarse", fr:"s'asseoir", ru:"сидеть", pt:"sentar", ar:"يجلس", hi:"बैठना", it:"sedersi"},
  "서다": {en:"to stand", zh:"站", ja:"立つ", es:"estar de pie", fr:"se tenir debout", ru:"стоять", pt:"ficar de pé", ar:"يقف", hi:"खड़े होना", it:"stare in piedi"},
  "듣다": {en:"to listen", zh:"听", ja:"聞く", es:"escuchar", fr:"écouter", ru:"слушать", pt:"ouvir", ar:"يستمع", hi:"सुनना", it:"ascoltare"},
  "말하다": {en:"to speak", zh:"说", ja:"話す", es:"hablar", fr:"parler", ru:"говорить", pt:"falar", ar:"يتكلم", hi:"बोलना", it:"parlare"},
  "알다": {en:"to know", zh:"知道", ja:"知る", es:"saber", fr:"savoir", ru:"знать", pt:"saber", ar:"يعرف", hi:"जानना", it:"sapere"},
  "찾다": {en:"to find", zh:"找", ja:"探す", es:"buscar", fr:"chercher", ru:"искать", pt:"procurar", ar:"يبحث", hi:"ढूँढना", it:"cercare"},
  "만나다": {en:"to meet", zh:"见面", ja:"会う", es:"encontrarse", fr:"rencontrer", ru:"встречать", pt:"encontrar", ar:"يقابل", hi:"मिलना", it:"incontrare"},
  "돕다": {en:"to help", zh:"帮助", ja:"助ける", es:"ayudar", fr:"aider", ru:"помогать", pt:"ajudar", ar:"يساعد", hi:"मदद करना", it:"aiutare"},
  "기다리다": {en:"to wait", zh:"等", ja:"待つ", es:"esperar", fr:"attendre", ru:"ждать", pt:"esperar", ar:"ينتظر", hi:"इंतज़ार करना", it:"aspettare"},
  "노래하다": {en:"to sing", zh:"唱歌", ja:"歌う", es:"cantar", fr:"chanter", ru:"петь", pt:"cantar", ar:"يغني", hi:"गाना", it:"cantare"},
  "일하다": {en:"to work", zh:"工作", ja:"働く", es:"trabajar", fr:"travailler", ru:"работать", pt:"trabalhar", ar:"يعمل", hi:"काम करना", it:"lavorare"},
  "쉬다": {en:"to rest", zh:"休息", ja:"休む", es:"descansar", fr:"se reposer", ru:"отдыхать", pt:"descansar", ar:"يستريح", hi:"आराम करना", it:"riposare"},
  "살다": {en:"to live", zh:"活／住", ja:"住む", es:"vivir", fr:"vivre", ru:"жить", pt:"viver", ar:"يعيش", hi:"रहना", it:"vivere"},
  "죽다": {en:"to die", zh:"死", ja:"死ぬ", es:"morir", fr:"mourir", ru:"умирать", pt:"morrer", ar:"يموت", hi:"मरना", it:"morire"},
  "길다": {en:"to be long", zh:"长", ja:"長い", es:"largo", fr:"long", ru:"длинный", pt:"longo", ar:"طويل", hi:"लंबा", it:"lungo"},
  "짧다": {en:"to be short", zh:"短", ja:"短い", es:"corto", fr:"court", ru:"короткий", pt:"curto", ar:"قصير", hi:"छोटा", it:"corto"},
  "빠르다": {en:"to be fast", zh:"快", ja:"速い", es:"rápido", fr:"rapide", ru:"быстрый", pt:"rápido", ar:"سريع", hi:"तेज़", it:"veloce"},
  "느리다": {en:"to be slow", zh:"慢", ja:"遅い", es:"lento", fr:"lent", ru:"медленный", pt:"lento", ar:"بطيء", hi:"धीमा", it:"lento"},
  "예쁘다": {en:"to be pretty", zh:"漂亮", ja:"きれい", es:"bonito", fr:"joli", ru:"красивый", pt:"bonito", ar:"جميل", hi:"सुंदर", it:"carino"},
  "맛있다": {en:"to be delicious", zh:"好吃", ja:"おいしい", es:"delicioso", fr:"délicieux", ru:"вкусный", pt:"delicioso", ar:"لذيذ", hi:"स्वादिष्ट", it:"delizioso"},
  "행복하다": {en:"to be happy", zh:"幸福", ja:"幸せ", es:"feliz", fr:"heureux", ru:"счастливый", pt:"feliz", ar:"سعيد", hi:"खुश", it:"felice"},
  "슬프다": {en:"to be sad", zh:"伤心", ja:"悲しい", es:"triste", fr:"triste", ru:"грустный", pt:"triste", ar:"حزين", hi:"उदास", it:"triste"},

  // ── batch 3 ──
  // people
  "아내": {en:"wife", zh:"妻子", ja:"妻", es:"esposa", fr:"femme", ru:"жена", pt:"esposa", ar:"زوجة", hi:"पत्नी", it:"moglie"},
  "남편": {en:"husband", zh:"丈夫", ja:"夫", es:"esposo", fr:"mari", ru:"муж", pt:"marido", ar:"زوج", hi:"पति", it:"marito"},
  "아저씨": {en:"mister / middle-aged man", zh:"叔叔", ja:"おじさん", es:"señor", fr:"monsieur", ru:"дядя", pt:"senhor", ar:"عم", hi:"अंकल", it:"signore"},
  "아줌마": {en:"ma'am / middle-aged woman", zh:"阿姨", ja:"おばさん", es:"señora", fr:"madame", ru:"тётя", pt:"senhora", ar:"خالة", hi:"आंटी", it:"signora"},
  "손님": {en:"guest / customer", zh:"客人", ja:"お客さん", es:"invitado", fr:"invité", ru:"гость", pt:"convidado", ar:"ضيف", hi:"मेहमान", it:"ospite"},
  "이웃": {en:"neighbor", zh:"邻居", ja:"隣人", es:"vecino", fr:"voisin", ru:"сосед", pt:"vizinho", ar:"جار", hi:"पड़ोसी", it:"vicino"},
  "부모": {en:"parents", zh:"父母", ja:"両親", es:"padres", fr:"parents", ru:"родители", pt:"pais", ar:"والدان", hi:"माता-पिता", it:"genitori"},
  "어른": {en:"adult", zh:"大人", ja:"大人", es:"adulto", fr:"adulte", ru:"взрослый", pt:"adulto", ar:"بالغ", hi:"वयस्क", it:"adulto"},
  "사장": {en:"boss / company head", zh:"老板", ja:"社長", es:"jefe", fr:"patron", ru:"начальник", pt:"chefe", ar:"مدير", hi:"मालिक", it:"capo"},
  "공주": {en:"princess", zh:"公主", ja:"お姫様", es:"princesa", fr:"princesse", ru:"принцесса", pt:"princesa", ar:"أميرة", hi:"राजकुमारी", it:"principessa"},
  "군인": {en:"soldier", zh:"军人", ja:"軍人", es:"soldado", fr:"soldat", ru:"солдат", pt:"soldado", ar:"جندي", hi:"सैनिक", it:"soldato"},
  "농부": {en:"farmer", zh:"农民", ja:"農夫", es:"granjero", fr:"fermier", ru:"фермер", pt:"agricultor", ar:"مزارع", hi:"किसान", it:"contadino"},

  // body
  "이마": {en:"forehead", zh:"额头", ja:"額", es:"frente", fr:"front", ru:"лоб", pt:"testa", ar:"جبين", hi:"माथा", it:"fronte"},
  "볼": {en:"cheek", zh:"脸颊", ja:"頬", es:"mejilla", fr:"joue", ru:"щека", pt:"bochecha", ar:"خد", hi:"गाल", it:"guancia"},
  "턱": {en:"chin / jaw", zh:"下巴", ja:"あご", es:"barbilla", fr:"menton", ru:"подбородок", pt:"queixo", ar:"ذقن", hi:"ठोड़ी", it:"mento"},
  "입술": {en:"lips", zh:"嘴唇", ja:"唇", es:"labios", fr:"lèvres", ru:"губы", pt:"lábios", ar:"شفاه", hi:"होंठ", it:"labbra"},
  "팔": {en:"arm", zh:"手臂", ja:"腕", es:"brazo", fr:"bras", ru:"рука", pt:"braço", ar:"ذراع", hi:"बाँह", it:"braccio"},
  "다리": {en:"leg / bridge", zh:"腿／桥", ja:"脚／橋", es:"pierna / puente", fr:"jambe / pont", ru:"нога / мост", pt:"perna / ponte", ar:"ساق / جسر", hi:"टाँग / पुल", it:"gamba / ponte"},
  "발가락": {en:"toe", zh:"脚趾", ja:"足の指", es:"dedo del pie", fr:"orteil", ru:"палец ноги", pt:"dedo do pé", ar:"إصبع القدم", hi:"पैर की उंगली", it:"dito del piede"},
  "손톱": {en:"fingernail", zh:"指甲", ja:"爪", es:"uña", fr:"ongle", ru:"ноготь", pt:"unha", ar:"ظفر", hi:"नाख़ून", it:"unghia"},
  "피부": {en:"skin", zh:"皮肤", ja:"肌", es:"piel", fr:"peau", ru:"кожа", pt:"pele", ar:"جلد", hi:"त्वचा", it:"pelle"},
  "눈썹": {en:"eyebrow", zh:"眉毛", ja:"眉", es:"ceja", fr:"sourcil", ru:"бровь", pt:"sobrancelha", ar:"حاجب", hi:"भौंह", it:"sopracciglio"},
  "허리": {en:"waist / lower back", zh:"腰", ja:"腰", es:"cintura", fr:"taille", ru:"талия", pt:"cintura", ar:"خصر", hi:"कमर", it:"vita"},

  // food & cooking
  "쌀": {en:"(uncooked) rice", zh:"大米", ja:"米", es:"arroz crudo", fr:"riz cru", ru:"рис (сырой)", pt:"arroz cru", ar:"أرز", hi:"चावल", it:"riso"},
  "밀가루": {en:"flour", zh:"面粉", ja:"小麦粉", es:"harina", fr:"farine", ru:"мука", pt:"farinha", ar:"دقيق", hi:"आटा", it:"farina"},
  "기름": {en:"oil", zh:"油", ja:"油", es:"aceite", fr:"huile", ru:"масло", pt:"óleo", ar:"زيت", hi:"तेल", it:"olio"},
  "고추": {en:"chili pepper", zh:"辣椒", ja:"唐辛子", es:"chile", fr:"piment", ru:"перец чили", pt:"pimenta", ar:"فلفل حار", hi:"मिर्च", it:"peperoncino"},
  "만두": {en:"dumpling", zh:"饺子", ja:"餃子", es:"empanadilla", fr:"raviole", ru:"пельмени", pt:"dumpling", ar:"زلابية", hi:"मोमो", it:"raviolo"},
  "김밥": {en:"gimbap", zh:"紫菜包饭", ja:"キンパ", es:"gimbap", fr:"gimbap", ru:"кимпаб", pt:"gimbap", ar:"كيمباب", hi:"गिम्बाप", it:"gimbap"},
  "피자": {en:"pizza", zh:"披萨", ja:"ピザ", es:"pizza", fr:"pizza", ru:"пицца", pt:"pizza", ar:"بيتزا", hi:"पिज़्ज़ा", it:"pizza"},
  "햄버거": {en:"hamburger", zh:"汉堡", ja:"ハンバーガー", es:"hamburguesa", fr:"hamburger", ru:"гамбургер", pt:"hambúrguer", ar:"همبرغر", hi:"बर्गर", it:"hamburger"},
  "샐러드": {en:"salad", zh:"沙拉", ja:"サラダ", es:"ensalada", fr:"salade", ru:"салат", pt:"salada", ar:"سلطة", hi:"सलाद", it:"insalata"},
  "포크": {en:"fork", zh:"叉子", ja:"フォーク", es:"tenedor", fr:"fourchette", ru:"вилка", pt:"garfo", ar:"شوكة", hi:"काँटा", it:"forchetta"},
  "냄비": {en:"pot", zh:"锅", ja:"鍋", es:"olla", fr:"casserole", ru:"кастрюля", pt:"panela", ar:"قدر", hi:"बर्तन", it:"pentola"},
  "감": {en:"persimmon", zh:"柿子", ja:"柿", es:"caqui", fr:"kaki", ru:"хурма", pt:"caqui", ar:"كاكا", hi:"तेंदू", it:"cachi"},
  "배추": {en:"napa cabbage", zh:"白菜", ja:"白菜", es:"col china", fr:"chou chinois", ru:"пекинская капуста", pt:"acelga chinesa", ar:"ملفوف صيني", hi:"चीनी गोभी", it:"cavolo cinese"},
  "상추": {en:"lettuce", zh:"生菜", ja:"レタス", es:"lechuga", fr:"laitue", ru:"салат-латук", pt:"alface", ar:"خس", hi:"सलाद पत्ता", it:"lattuga"},
  "토마토": {en:"tomato", zh:"番茄", ja:"トマト", es:"tomate", fr:"tomate", ru:"помидор", pt:"tomate", ar:"طماطم", hi:"टमाटर", it:"pomodoro"},
  "옥수수": {en:"corn", zh:"玉米", ja:"とうもろこし", es:"maíz", fr:"maïs", ru:"кукуруза", pt:"milho", ar:"ذرة", hi:"मक्का", it:"mais"},
  "고구마": {en:"sweet potato", zh:"红薯", ja:"さつまいも", es:"batata", fr:"patate douce", ru:"батат", pt:"batata-doce", ar:"بطاطا حلوة", hi:"शकरकंद", it:"patata dolce"},
  "호박": {en:"pumpkin", zh:"南瓜", ja:"かぼちゃ", es:"calabaza", fr:"citrouille", ru:"тыква", pt:"abóbora", ar:"يقطين", hi:"कद्दू", it:"zucca"},
  "귤": {en:"tangerine", zh:"橘子", ja:"みかん", es:"mandarina", fr:"mandarine", ru:"мандарин", pt:"tangerina", ar:"يوسفي", hi:"कीनू", it:"mandarino"},
  "맥주": {en:"beer", zh:"啤酒", ja:"ビール", es:"cerveza", fr:"bière", ru:"пиво", pt:"cerveja", ar:"بيرة", hi:"बीयर", it:"birra"},
  "와인": {en:"wine", zh:"葡萄酒", ja:"ワイン", es:"vino", fr:"vin", ru:"вино", pt:"vinho", ar:"نبيذ", hi:"वाइन", it:"vino"},

  // nature
  "땅": {en:"ground / land", zh:"土地", ja:"地面", es:"tierra", fr:"terre", ru:"земля", pt:"terra", ar:"أرض", hi:"ज़मीन", it:"terra"},
  "흙": {en:"soil / dirt", zh:"泥土", ja:"土", es:"tierra", fr:"sol", ru:"почва", pt:"solo", ar:"تراب", hi:"मिट्टी", it:"terra"},
  "모래": {en:"sand", zh:"沙子", ja:"砂", es:"arena", fr:"sable", ru:"песок", pt:"areia", ar:"رمل", hi:"रेत", it:"sabbia"},
  "바위": {en:"rock / boulder", zh:"岩石", ja:"岩", es:"roca", fr:"rocher", ru:"скала", pt:"rocha", ar:"صخرة", hi:"चट्टान", it:"roccia"},
  "언덕": {en:"hill", zh:"山丘", ja:"丘", es:"colina", fr:"colline", ru:"холм", pt:"colina", ar:"تل", hi:"पहाड़ी", it:"collina"},
  "폭포": {en:"waterfall", zh:"瀑布", ja:"滝", es:"cascada", fr:"cascade", ru:"водопад", pt:"cachoeira", ar:"شلال", hi:"झरना", it:"cascata"},
  "번개": {en:"lightning", zh:"闪电", ja:"稲妻", es:"relámpago", fr:"éclair", ru:"молния", pt:"relâmpago", ar:"برق", hi:"बिजली", it:"fulmine"},
  "천둥": {en:"thunder", zh:"雷", ja:"雷", es:"trueno", fr:"tonnerre", ru:"гром", pt:"trovão", ar:"رعد", hi:"गरज", it:"tuono"},
  "안개": {en:"fog", zh:"雾", ja:"霧", es:"niebla", fr:"brouillard", ru:"туман", pt:"neblina", ar:"ضباب", hi:"कोहरा", it:"nebbia"},
  "그림자": {en:"shadow", zh:"影子", ja:"影", es:"sombra", fr:"ombre", ru:"тень", pt:"sombra", ar:"ظل", hi:"परछाई", it:"ombra"},
  "파도": {en:"wave", zh:"波浪", ja:"波", es:"ola", fr:"vague", ru:"волна", pt:"onda", ar:"موجة", hi:"लहर", it:"onda"},
  "이슬": {en:"dew", zh:"露水", ja:"露", es:"rocío", fr:"rosée", ru:"роса", pt:"orvalho", ar:"ندى", hi:"ओस", it:"rugiada"},

  // plants
  "잎": {en:"leaf", zh:"叶子", ja:"葉", es:"hoja", fr:"feuille", ru:"лист", pt:"folha", ar:"ورقة", hi:"पत्ता", it:"foglia"},
  "뿌리": {en:"root", zh:"根", ja:"根", es:"raíz", fr:"racine", ru:"корень", pt:"raiz", ar:"جذر", hi:"जड़", it:"radice"},
  "씨앗": {en:"seed", zh:"种子", ja:"種", es:"semilla", fr:"graine", ru:"семя", pt:"semente", ar:"بذرة", hi:"बीज", it:"seme"},
  "가지": {en:"branch / eggplant", zh:"树枝／茄子", ja:"枝／なす", es:"rama / berenjena", fr:"branche / aubergine", ru:"ветка / баклажан", pt:"galho / berinjela", ar:"غصن / باذنجان", hi:"टहनी / बैंगन", it:"ramo / melanzana"},
  "장미": {en:"rose", zh:"玫瑰", ja:"バラ", es:"rosa", fr:"rose", ru:"роза", pt:"rosa", ar:"وردة", hi:"गुलाब", it:"rosa"},
  "해바라기": {en:"sunflower", zh:"向日葵", ja:"ひまわり", es:"girasol", fr:"tournesol", ru:"подсолнух", pt:"girassol", ar:"دوار الشمس", hi:"सूरजमुखी", it:"girasole"},
  "대나무": {en:"bamboo", zh:"竹子", ja:"竹", es:"bambú", fr:"bambou", ru:"бамбук", pt:"bambu", ar:"خيزران", hi:"बाँस", it:"bambù"},
  "소나무": {en:"pine tree", zh:"松树", ja:"松", es:"pino", fr:"pin", ru:"сосна", pt:"pinheiro", ar:"صنوبر", hi:"चीड़", it:"pino"},

  // places
  "교회": {en:"church", zh:"教堂", ja:"教会", es:"iglesia", fr:"église", ru:"церковь", pt:"igreja", ar:"كنيسة", hi:"चर्च", it:"chiesa"},
  "절": {en:"(Buddhist) temple", zh:"寺庙", ja:"寺", es:"templo", fr:"temple", ru:"храм", pt:"templo", ar:"معبد", hi:"मंदिर", it:"tempio"},
  "은행": {en:"bank", zh:"银行", ja:"銀行", es:"banco", fr:"banque", ru:"банк", pt:"banco", ar:"بنك", hi:"बैंक", it:"banca"},
  "우체국": {en:"post office", zh:"邮局", ja:"郵便局", es:"correos", fr:"poste", ru:"почта", pt:"correios", ar:"مكتب بريد", hi:"डाकघर", it:"ufficio postale"},
  "역": {en:"station", zh:"车站", ja:"駅", es:"estación", fr:"gare", ru:"станция", pt:"estação", ar:"محطة", hi:"स्टेशन", it:"stazione"},
  "공항": {en:"airport", zh:"机场", ja:"空港", es:"aeropuerto", fr:"aéroport", ru:"аэропорт", pt:"aeroporto", ar:"مطار", hi:"हवाई अड्डा", it:"aeroporto"},
  "식당": {en:"restaurant", zh:"餐厅", ja:"食堂", es:"restaurante", fr:"restaurant", ru:"ресторан", pt:"restaurante", ar:"مطعم", hi:"रेस्तराँ", it:"ristorante"},
  "카페": {en:"cafe", zh:"咖啡厅", ja:"カフェ", es:"café", fr:"café", ru:"кафе", pt:"café", ar:"مقهى", hi:"कैफ़े", it:"caffè"},
  "극장": {en:"theater", zh:"剧场", ja:"劇場", es:"teatro", fr:"théâtre", ru:"театр", pt:"teatro", ar:"مسرح", hi:"थिएटर", it:"teatro"},
  "도서관": {en:"library", zh:"图书馆", ja:"図書館", es:"biblioteca", fr:"bibliothèque", ru:"библиотека", pt:"biblioteca", ar:"مكتبة", hi:"पुस्तकालय", it:"biblioteca"},
  "박물관": {en:"museum", zh:"博物馆", ja:"博物館", es:"museo", fr:"musée", ru:"музей", pt:"museu", ar:"متحف", hi:"संग्रहालय", it:"museo"},
  "동물원": {en:"zoo", zh:"动物园", ja:"動物園", es:"zoológico", fr:"zoo", ru:"зоопарк", pt:"zoológico", ar:"حديقة حيوان", hi:"चिड़ियाघर", it:"zoo"},
  "놀이터": {en:"playground", zh:"游乐场", ja:"遊び場", es:"parque infantil", fr:"aire de jeux", ru:"детская площадка", pt:"parquinho", ar:"ملعب", hi:"खेल का मैदान", it:"parco giochi"},
  "수영장": {en:"swimming pool", zh:"游泳池", ja:"プール", es:"piscina", fr:"piscine", ru:"бассейн", pt:"piscina", ar:"مسبح", hi:"स्विमिंग पूल", it:"piscina"},
  "화장실": {en:"toilet / restroom", zh:"厕所", ja:"トイレ", es:"baño", fr:"toilettes", ru:"туалет", pt:"banheiro", ar:"حمام", hi:"शौचालय", it:"bagno"},
  "부엌": {en:"kitchen", zh:"厨房", ja:"台所", es:"cocina", fr:"cuisine", ru:"кухня", pt:"cozinha", ar:"مطبخ", hi:"रसोई", it:"cucina"},
  "교실": {en:"classroom", zh:"教室", ja:"教室", es:"aula", fr:"salle de classe", ru:"класс", pt:"sala de aula", ar:"فصل", hi:"कक्षा", it:"aula"},
  "호텔": {en:"hotel", zh:"酒店", ja:"ホテル", es:"hotel", fr:"hôtel", ru:"отель", pt:"hotel", ar:"فندق", hi:"होटल", it:"hotel"},

  // home & objects
  "창문": {en:"window", zh:"窗户", ja:"窓", es:"ventana", fr:"fenêtre", ru:"окно", pt:"janela", ar:"نافذة", hi:"खिड़की", it:"finestra"},
  "책상": {en:"desk", zh:"书桌", ja:"机", es:"escritorio", fr:"bureau", ru:"стол", pt:"escrivaninha", ar:"مكتب", hi:"मेज़", it:"scrivania"},
  "침대": {en:"bed", zh:"床", ja:"ベッド", es:"cama", fr:"lit", ru:"кровать", pt:"cama", ar:"سرير", hi:"बिस्तर", it:"letto"},
  "소파": {en:"sofa", zh:"沙发", ja:"ソファ", es:"sofá", fr:"canapé", ru:"диван", pt:"sofá", ar:"أريكة", hi:"सोफ़ा", it:"divano"},
  "거울": {en:"mirror", zh:"镜子", ja:"鏡", es:"espejo", fr:"miroir", ru:"зеркало", pt:"espelho", ar:"مرآة", hi:"आईना", it:"specchio"},
  "열쇠": {en:"key", zh:"钥匙", ja:"鍵", es:"llave", fr:"clé", ru:"ключ", pt:"chave", ar:"مفتاح", hi:"चाबी", it:"chiave"},
  "달력": {en:"calendar", zh:"日历", ja:"カレンダー", es:"calendario", fr:"calendrier", ru:"календарь", pt:"calendário", ar:"تقويم", hi:"कैलेंडर", it:"calendario"},
  "연필": {en:"pencil", zh:"铅笔", ja:"鉛筆", es:"lápiz", fr:"crayon", ru:"карандаш", pt:"lápis", ar:"قلم رصاص", hi:"पेंसिल", it:"matita"},
  "공책": {en:"notebook", zh:"笔记本", ja:"ノート", es:"cuaderno", fr:"cahier", ru:"тетрадь", pt:"caderno", ar:"دفتر", hi:"कॉपी", it:"quaderno"},
  "지우개": {en:"eraser", zh:"橡皮", ja:"消しゴム", es:"goma", fr:"gomme", ru:"ластик", pt:"borracha", ar:"ممحاة", hi:"रबर", it:"gomma"},
  "컴퓨터": {en:"computer", zh:"电脑", ja:"コンピューター", es:"computadora", fr:"ordinateur", ru:"компьютер", pt:"computador", ar:"حاسوب", hi:"कंप्यूटर", it:"computer"},
  "카메라": {en:"camera", zh:"相机", ja:"カメラ", es:"cámara", fr:"appareil photo", ru:"камера", pt:"câmera", ar:"كاميرا", hi:"कैमरा", it:"fotocamera"},
  "텔레비전": {en:"television", zh:"电视", ja:"テレビ", es:"televisión", fr:"télévision", ru:"телевизор", pt:"televisão", ar:"تلفاز", hi:"टीवी", it:"televisione"},
  "라디오": {en:"radio", zh:"收音机", ja:"ラジオ", es:"radio", fr:"radio", ru:"радио", pt:"rádio", ar:"راديو", hi:"रेडियो", it:"radio"},
  "선풍기": {en:"electric fan", zh:"风扇", ja:"扇風機", es:"ventilador", fr:"ventilateur", ru:"вентилятор", pt:"ventilador", ar:"مروحة", hi:"पंखा", it:"ventilatore"},
  "양초": {en:"candle", zh:"蜡烛", ja:"ろうそく", es:"vela", fr:"bougie", ru:"свеча", pt:"vela", ar:"شمعة", hi:"मोमबत्ती", it:"candela"},
  "칫솔": {en:"toothbrush", zh:"牙刷", ja:"歯ブラシ", es:"cepillo de dientes", fr:"brosse à dents", ru:"зубная щётка", pt:"escova de dentes", ar:"فرشاة أسنان", hi:"टूथब्रश", it:"spazzolino"},
  "치약": {en:"toothpaste", zh:"牙膏", ja:"歯磨き粉", es:"pasta de dientes", fr:"dentifrice", ru:"зубная паста", pt:"pasta de dente", ar:"معجون أسنان", hi:"टूथपेस्ट", it:"dentifricio"},
  "휴지": {en:"tissue / toilet paper", zh:"纸巾", ja:"ティッシュ", es:"pañuelo de papel", fr:"mouchoir", ru:"салфетка", pt:"lenço de papel", ar:"مناديل", hi:"टिशू", it:"fazzoletto"},
  "지갑": {en:"wallet", zh:"钱包", ja:"財布", es:"cartera", fr:"portefeuille", ru:"кошелёк", pt:"carteira", ar:"محفظة", hi:"बटुआ", it:"portafoglio"},

  // clothes
  "셔츠": {en:"shirt", zh:"衬衫", ja:"シャツ", es:"camisa", fr:"chemise", ru:"рубашка", pt:"camisa", ar:"قميص", hi:"शर्ट", it:"camicia"},
  "티셔츠": {en:"t-shirt", zh:"T恤", ja:"Tシャツ", es:"camiseta", fr:"t-shirt", ru:"футболка", pt:"camiseta", ar:"تي شيرت", hi:"टी-शर्ट", it:"maglietta"},
  "코트": {en:"coat", zh:"大衣", ja:"コート", es:"abrigo", fr:"manteau", ru:"пальто", pt:"casaco", ar:"معطف", hi:"कोट", it:"cappotto"},
  "스웨터": {en:"sweater", zh:"毛衣", ja:"セーター", es:"suéter", fr:"pull", ru:"свитер", pt:"suéter", ar:"سترة", hi:"स्वेटर", it:"maglione"},
  "드레스": {en:"dress", zh:"连衣裙", ja:"ドレス", es:"vestido", fr:"robe", ru:"платье", pt:"vestido", ar:"فستان", hi:"ड्रेस", it:"vestito"},
  "벨트": {en:"belt", zh:"腰带", ja:"ベルト", es:"cinturón", fr:"ceinture", ru:"ремень", pt:"cinto", ar:"حزام", hi:"बेल्ट", it:"cintura"},
  "목도리": {en:"scarf", zh:"围巾", ja:"マフラー", es:"bufanda", fr:"écharpe", ru:"шарф", pt:"cachecol", ar:"وشاح", hi:"मफ़लर", it:"sciarpa"},
  "운동화": {en:"sneakers", zh:"运动鞋", ja:"スニーカー", es:"zapatillas", fr:"baskets", ru:"кроссовки", pt:"tênis", ar:"حذاء رياضي", hi:"स्नीकर्स", it:"scarpe da ginnastica"},

  // vehicles
  "지하철": {en:"subway", zh:"地铁", ja:"地下鉄", es:"metro", fr:"métro", ru:"метро", pt:"metrô", ar:"مترو", hi:"मेट्रो", it:"metropolitana"},
  "트럭": {en:"truck", zh:"卡车", ja:"トラック", es:"camión", fr:"camion", ru:"грузовик", pt:"caminhão", ar:"شاحنة", hi:"ट्रक", it:"camion"},
  "오토바이": {en:"motorcycle", zh:"摩托车", ja:"バイク", es:"motocicleta", fr:"moto", ru:"мотоцикл", pt:"moto", ar:"دراجة نارية", hi:"मोटरसाइकिल", it:"moto"},
  "헬리콥터": {en:"helicopter", zh:"直升机", ja:"ヘリコプター", es:"helicóptero", fr:"hélicoptère", ru:"вертолёт", pt:"helicóptero", ar:"مروحية", hi:"हेलीकॉप्टर", it:"elicottero"},
  "로켓": {en:"rocket", zh:"火箭", ja:"ロケット", es:"cohete", fr:"fusée", ru:"ракета", pt:"foguete", ar:"صاروخ", hi:"रॉकेट", it:"razzo"},
  "자동차": {en:"car / automobile", zh:"汽车", ja:"自動車", es:"coche", fr:"voiture", ru:"машина", pt:"carro", ar:"سيارة", hi:"कार", it:"automobile"},

  // time
  "년": {en:"year", zh:"年", ja:"年", es:"año", fr:"an", ru:"год", pt:"ano", ar:"سنة", hi:"साल", it:"anno"},
  "날": {en:"day", zh:"天", ja:"日", es:"día", fr:"jour", ru:"день", pt:"dia", ar:"يوم", hi:"दिन", it:"giorno"},
  "주": {en:"week", zh:"周", ja:"週", es:"semana", fr:"semaine", ru:"неделя", pt:"semana", ar:"أسبوع", hi:"सप्ताह", it:"settimana"},
  "하루": {en:"one day", zh:"一天", ja:"一日", es:"un día", fr:"une journée", ru:"один день", pt:"um dia", ar:"يوم واحد", hi:"एक दिन", it:"un giorno"},
  "분": {en:"minute", zh:"分钟", ja:"分", es:"minuto", fr:"minute", ru:"минута", pt:"minuto", ar:"دقيقة", hi:"मिनट", it:"minuto"},
  "초": {en:"second", zh:"秒", ja:"秒", es:"segundo", fr:"seconde", ru:"секунда", pt:"segundo", ar:"ثانية", hi:"सेकंड", it:"secondo"},
  "올해": {en:"this year", zh:"今年", ja:"今年", es:"este año", fr:"cette année", ru:"этот год", pt:"este ano", ar:"هذا العام", hi:"इस साल", it:"quest'anno"},
  "처음": {en:"first / beginning", zh:"开始", ja:"初め", es:"primero", fr:"début", ru:"начало", pt:"início", ar:"بداية", hi:"शुरुआत", it:"inizio"},
  "끝": {en:"end", zh:"结束", ja:"終わり", es:"fin", fr:"fin", ru:"конец", pt:"fim", ar:"نهاية", hi:"अंत", it:"fine"},
  "오후": {en:"afternoon", zh:"下午", ja:"午後", es:"tarde", fr:"après-midi", ru:"день", pt:"tarde", ar:"بعد الظهر", hi:"दोपहर", it:"pomeriggio"},

  // colors
  "검정": {en:"black", zh:"黑色", ja:"黒", es:"negro", fr:"noir", ru:"чёрный", pt:"preto", ar:"أسود", hi:"काला", it:"nero"},
  "하양": {en:"white", zh:"白色", ja:"白", es:"blanco", fr:"blanc", ru:"белый", pt:"branco", ar:"أبيض", hi:"सफ़ेद", it:"bianco"},
  "보라": {en:"purple", zh:"紫色", ja:"紫", es:"morado", fr:"violet", ru:"фиолетовый", pt:"roxo", ar:"بنفسجي", hi:"बैंगनी", it:"viola"},
  "분홍": {en:"pink", zh:"粉色", ja:"ピンク", es:"rosa", fr:"rose", ru:"розовый", pt:"rosa", ar:"وردي", hi:"गुलाबी", it:"rosa"},
  "주황": {en:"orange (color)", zh:"橙色", ja:"オレンジ色", es:"naranja", fr:"orange", ru:"оранжевый", pt:"laranja", ar:"برتقالي", hi:"नारंगी", it:"arancione"},
  "갈색": {en:"brown", zh:"棕色", ja:"茶色", es:"marrón", fr:"marron", ru:"коричневый", pt:"marrom", ar:"بني", hi:"भूरा", it:"marrone"},
  "회색": {en:"gray", zh:"灰色", ja:"灰色", es:"gris", fr:"gris", ru:"серый", pt:"cinza", ar:"رمادي", hi:"धूसर", it:"grigio"},

  // numbers (sino)
  "백": {en:"hundred", zh:"百", ja:"百", es:"cien", fr:"cent", ru:"сто", pt:"cem", ar:"مئة", hi:"सौ", it:"cento"},
  "천": {en:"thousand", zh:"千", ja:"千", es:"mil", fr:"mille", ru:"тысяча", pt:"mil", ar:"ألف", hi:"हज़ार", it:"mille"},
  "만": {en:"ten thousand", zh:"万", ja:"万", es:"diez mil", fr:"dix mille", ru:"десять тысяч", pt:"dez mil", ar:"عشرة آلاف", hi:"दस हज़ार", it:"diecimila"},
  "영": {en:"zero", zh:"零", ja:"ゼロ", es:"cero", fr:"zéro", ru:"ноль", pt:"zero", ar:"صفر", hi:"शून्य", it:"zero"},
  "반": {en:"half", zh:"一半", ja:"半分", es:"mitad", fr:"moitié", ru:"половина", pt:"metade", ar:"نصف", hi:"आधा", it:"metà"},

  // directions & demonstratives
  "여기": {en:"here", zh:"这里", ja:"ここ", es:"aquí", fr:"ici", ru:"здесь", pt:"aqui", ar:"هنا", hi:"यहाँ", it:"qui"},
  "거기": {en:"there", zh:"那里", ja:"そこ", es:"ahí", fr:"là", ru:"там", pt:"aí", ar:"هناك", hi:"वहाँ", it:"lì"},
  "위": {en:"up / above", zh:"上面", ja:"上", es:"arriba", fr:"au-dessus", ru:"вверх", pt:"em cima", ar:"فوق", hi:"ऊपर", it:"sopra"},
  "아래": {en:"down / below", zh:"下面", ja:"下", es:"abajo", fr:"en bas", ru:"вниз", pt:"embaixo", ar:"تحت", hi:"नीचे", it:"sotto"},
  "앞": {en:"front", zh:"前面", ja:"前", es:"adelante", fr:"devant", ru:"впереди", pt:"frente", ar:"أمام", hi:"आगे", it:"davanti"},
  "뒤": {en:"back / behind", zh:"后面", ja:"後ろ", es:"atrás", fr:"derrière", ru:"сзади", pt:"atrás", ar:"خلف", hi:"पीछे", it:"dietro"},
  "안": {en:"inside", zh:"里面", ja:"中", es:"dentro", fr:"dedans", ru:"внутри", pt:"dentro", ar:"داخل", hi:"अंदर", it:"dentro"},
  "밖": {en:"outside", zh:"外面", ja:"外", es:"fuera", fr:"dehors", ru:"снаружи", pt:"fora", ar:"خارج", hi:"बाहर", it:"fuori"},
  "왼쪽": {en:"left", zh:"左边", ja:"左", es:"izquierda", fr:"gauche", ru:"слева", pt:"esquerda", ar:"يسار", hi:"बायाँ", it:"sinistra"},
  "오른쪽": {en:"right", zh:"右边", ja:"右", es:"derecha", fr:"droite", ru:"справа", pt:"direita", ar:"يمين", hi:"दायाँ", it:"destra"},
  "옆": {en:"beside / next to", zh:"旁边", ja:"横", es:"al lado", fr:"à côté", ru:"рядом", pt:"ao lado", ar:"بجانب", hi:"बगल", it:"accanto"},
  "사이": {en:"between", zh:"之间", ja:"間", es:"entre", fr:"entre", ru:"между", pt:"entre", ar:"بين", hi:"बीच", it:"tra"},

  // greetings & basics
  "네": {en:"yes", zh:"是", ja:"はい", es:"sí", fr:"oui", ru:"да", pt:"sim", ar:"نعم", hi:"हाँ", it:"sì"},
  "아니요": {en:"no", zh:"不", ja:"いいえ", es:"no", fr:"non", ru:"нет", pt:"não", ar:"لا", hi:"नहीं", it:"no"},
  "안녕": {en:"hi / bye", zh:"你好", ja:"こんにちは", es:"hola", fr:"salut", ru:"привет", pt:"oi", ar:"مرحبا", hi:"नमस्ते", it:"ciao"},
  "감사": {en:"thanks / gratitude", zh:"谢谢", ja:"感謝", es:"gracias", fr:"merci", ru:"спасибо", pt:"obrigado", ar:"شكرا", hi:"धन्यवाद", it:"grazie"},
  "미안": {en:"sorry", zh:"对不起", ja:"ごめん", es:"perdón", fr:"désolé", ru:"извини", pt:"desculpa", ar:"آسف", hi:"माफ़ी", it:"scusa"},

  // abstract / school
  "글": {en:"writing / text", zh:"文章", ja:"文", es:"texto", fr:"texte", ru:"текст", pt:"texto", ar:"نص", hi:"लेख", it:"testo"},
  "단어": {en:"word", zh:"单词", ja:"単語", es:"palabra", fr:"mot", ru:"слово", pt:"palavra", ar:"كلمة", hi:"शब्द", it:"parola"},
  "문장": {en:"sentence", zh:"句子", ja:"文", es:"oración", fr:"phrase", ru:"предложение", pt:"frase", ar:"جملة", hi:"वाक्य", it:"frase"},
  "질문": {en:"question", zh:"问题", ja:"質問", es:"pregunta", fr:"question", ru:"вопрос", pt:"pergunta", ar:"سؤال", hi:"सवाल", it:"domanda"},
  "숙제": {en:"homework", zh:"作业", ja:"宿題", es:"tarea", fr:"devoirs", ru:"домашнее задание", pt:"lição de casa", ar:"واجب", hi:"गृहकार्य", it:"compiti"},
  "시험": {en:"exam / test", zh:"考试", ja:"試験", es:"examen", fr:"examen", ru:"экзамен", pt:"prova", ar:"امتحان", hi:"परीक्षा", it:"esame"},
  "공부": {en:"study", zh:"学习", ja:"勉強", es:"estudio", fr:"étude", ru:"учёба", pt:"estudo", ar:"دراسة", hi:"पढ़ाई", it:"studio"},
  "노래": {en:"song", zh:"歌", ja:"歌", es:"canción", fr:"chanson", ru:"песня", pt:"canção", ar:"أغنية", hi:"गाना", it:"canzone"},
  "춤": {en:"dance", zh:"舞蹈", ja:"踊り", es:"baile", fr:"danse", ru:"танец", pt:"dança", ar:"رقص", hi:"नृत्य", it:"danza"},
  "영화": {en:"movie", zh:"电影", ja:"映画", es:"película", fr:"film", ru:"фильм", pt:"filme", ar:"فيلم", hi:"फ़िल्म", it:"film"},
  "음악": {en:"music", zh:"音乐", ja:"音楽", es:"música", fr:"musique", ru:"музыка", pt:"música", ar:"موسيقى", hi:"संगीत", it:"musica"},
  "이야기": {en:"story", zh:"故事", ja:"物語", es:"historia", fr:"histoire", ru:"история", pt:"história", ar:"قصة", hi:"कहानी", it:"storia"},
  "꿈": {en:"dream", zh:"梦", ja:"夢", es:"sueño", fr:"rêve", ru:"мечта", pt:"sonho", ar:"حلم", hi:"सपना", it:"sogno"},
  "생각": {en:"thought", zh:"想法", ja:"考え", es:"pensamiento", fr:"pensée", ru:"мысль", pt:"pensamento", ar:"فكرة", hi:"विचार", it:"pensiero"},
  "마음": {en:"mind / heart", zh:"心", ja:"心", es:"corazón", fr:"cœur", ru:"душа", pt:"coração", ar:"قلب", hi:"मन", it:"cuore"},
  "선물": {en:"gift / present", zh:"礼物", ja:"プレゼント", es:"regalo", fr:"cadeau", ru:"подарок", pt:"presente", ar:"هدية", hi:"उपहार", it:"regalo"},
  "약속": {en:"promise / appointment", zh:"约定", ja:"約束", es:"promesa", fr:"promesse", ru:"обещание", pt:"promessa", ar:"وعد", hi:"वादा", it:"promessa"},
  "비밀": {en:"secret", zh:"秘密", ja:"秘密", es:"secreto", fr:"secret", ru:"секрет", pt:"segredo", ar:"سر", hi:"राज़", it:"segreto"},
  "눈물": {en:"tears", zh:"眼泪", ja:"涙", es:"lágrimas", fr:"larmes", ru:"слёзы", pt:"lágrimas", ar:"دموع", hi:"आँसू", it:"lacrime"},
  "날씨": {en:"weather", zh:"天气", ja:"天気", es:"clima", fr:"temps", ru:"погода", pt:"tempo", ar:"طقس", hi:"मौसम", it:"tempo"},
  "약": {en:"medicine", zh:"药", ja:"薬", es:"medicina", fr:"médicament", ru:"лекарство", pt:"remédio", ar:"دواء", hi:"दवा", it:"medicina"},
  "병": {en:"illness / bottle", zh:"病／瓶子", ja:"病気／瓶", es:"enfermedad / botella", fr:"maladie / bouteille", ru:"болезнь / бутылка", pt:"doença / garrafa", ar:"مرض / زجاجة", hi:"बीमारी / बोतल", it:"malattia / bottiglia"},
  "건강": {en:"health", zh:"健康", ja:"健康", es:"salud", fr:"santé", ru:"здоровье", pt:"saúde", ar:"صحة", hi:"स्वास्थ्य", it:"salute"},
  "맛": {en:"taste / flavor", zh:"味道", ja:"味", es:"sabor", fr:"goût", ru:"вкус", pt:"sabor", ar:"طعم", hi:"स्वाद", it:"sapore"},

  // more verbs
  "열다": {en:"to open", zh:"打开", ja:"開ける", es:"abrir", fr:"ouvrir", ru:"открывать", pt:"abrir", ar:"يفتح", hi:"खोलना", it:"aprire"},
  "닫다": {en:"to close", zh:"关", ja:"閉める", es:"cerrar", fr:"fermer", ru:"закрывать", pt:"fechar", ar:"يغلق", hi:"बंद करना", it:"chiudere"},
  "씻다": {en:"to wash", zh:"洗", ja:"洗う", es:"lavar", fr:"laver", ru:"мыть", pt:"lavar", ar:"يغسل", hi:"धोना", it:"lavare"},
  "입다": {en:"to wear", zh:"穿", ja:"着る", es:"ponerse", fr:"porter", ru:"надевать", pt:"vestir", ar:"يرتدي", hi:"पहनना", it:"indossare"},
  "배우다": {en:"to learn", zh:"学", ja:"学ぶ", es:"aprender", fr:"apprendre", ru:"учиться", pt:"aprender", ar:"يتعلم", hi:"सीखना", it:"imparare"},
  "가르치다": {en:"to teach", zh:"教", ja:"教える", es:"enseñar", fr:"enseigner", ru:"учить", pt:"ensinar", ar:"يُعلّم", hi:"सिखाना", it:"insegnare"},
  "생각하다": {en:"to think", zh:"想", ja:"考える", es:"pensar", fr:"penser", ru:"думать", pt:"pensar", ar:"يفكر", hi:"सोचना", it:"pensare"},
  "기억하다": {en:"to remember", zh:"记住", ja:"覚える", es:"recordar", fr:"se souvenir", ru:"помнить", pt:"lembrar", ar:"يتذكر", hi:"याद रखना", it:"ricordare"},
  "잊다": {en:"to forget", zh:"忘记", ja:"忘れる", es:"olvidar", fr:"oublier", ru:"забывать", pt:"esquecer", ar:"ينسى", hi:"भूलना", it:"dimenticare"},
  "던지다": {en:"to throw", zh:"扔", ja:"投げる", es:"lanzar", fr:"lancer", ru:"бросать", pt:"jogar", ar:"يرمي", hi:"फेंकना", it:"lanciare"},
  "잡다": {en:"to catch / grab", zh:"抓", ja:"つかむ", es:"agarrar", fr:"attraper", ru:"ловить", pt:"pegar", ar:"يمسك", hi:"पकड़ना", it:"afferrare"},
  "밀다": {en:"to push", zh:"推", ja:"押す", es:"empujar", fr:"pousser", ru:"толкать", pt:"empurrar", ar:"يدفع", hi:"धकेलना", it:"spingere"},
  "당기다": {en:"to pull", zh:"拉", ja:"引く", es:"tirar", fr:"tirer", ru:"тянуть", pt:"puxar", ar:"يسحب", hi:"खींचना", it:"tirare"},
  "들다": {en:"to lift / hold", zh:"举", ja:"持ち上げる", es:"levantar", fr:"soulever", ru:"поднимать", pt:"levantar", ar:"يرفع", hi:"उठाना", it:"sollevare"},
  "놓다": {en:"to put down", zh:"放", ja:"置く", es:"poner", fr:"poser", ru:"класть", pt:"colocar", ar:"يضع", hi:"रखना", it:"posare"},
  "자르다": {en:"to cut", zh:"剪", ja:"切る", es:"cortar", fr:"couper", ru:"резать", pt:"cortar", ar:"يقطع", hi:"काटना", it:"tagliare"},
  "그리다": {en:"to draw", zh:"画", ja:"描く", es:"dibujar", fr:"dessiner", ru:"рисовать", pt:"desenhar", ar:"يرسم", hi:"चित्र बनाना", it:"disegnare"},
  "춤추다": {en:"to dance", zh:"跳舞", ja:"踊る", es:"bailar", fr:"danser", ru:"танцевать", pt:"dançar", ar:"يرقص", hi:"नाचना", it:"ballare"},
  "요리하다": {en:"to cook", zh:"做饭", ja:"料理する", es:"cocinar", fr:"cuisiner", ru:"готовить", pt:"cozinhar", ar:"يطبخ", hi:"खाना बनाना", it:"cucinare"},
  "청소하다": {en:"to clean", zh:"打扫", ja:"掃除する", es:"limpiar", fr:"nettoyer", ru:"убирать", pt:"limpar", ar:"ينظف", hi:"सफ़ाई करना", it:"pulire"},
  "운전하다": {en:"to drive", zh:"开车", ja:"運転する", es:"conducir", fr:"conduire", ru:"водить", pt:"dirigir", ar:"يقود", hi:"गाड़ी चलाना", it:"guidare"},
  "시작하다": {en:"to start", zh:"开始", ja:"始める", es:"empezar", fr:"commencer", ru:"начинать", pt:"começar", ar:"يبدأ", hi:"शुरू करना", it:"iniziare"},
  "좋아하다": {en:"to like", zh:"喜欢", ja:"好き", es:"gustar", fr:"aimer", ru:"нравиться", pt:"gostar", ar:"يحب", hi:"पसंद करना", it:"piacere"},
  "사랑하다": {en:"to love", zh:"爱", ja:"愛する", es:"amar", fr:"aimer", ru:"любить", pt:"amar", ar:"يحب", hi:"प्यार करना", it:"amare"},

  // more adjectives
  "높다": {en:"to be high / tall", zh:"高", ja:"高い", es:"alto", fr:"haut", ru:"высокий", pt:"alto", ar:"عالٍ", hi:"ऊँचा", it:"alto"},
  "낮다": {en:"to be low", zh:"低", ja:"低い", es:"bajo", fr:"bas", ru:"низкий", pt:"baixo", ar:"منخفض", hi:"नीचा", it:"basso"},
  "넓다": {en:"to be wide / spacious", zh:"宽", ja:"広い", es:"ancho", fr:"large", ru:"широкий", pt:"largo", ar:"واسع", hi:"चौड़ा", it:"largo"},
  "무겁다": {en:"to be heavy", zh:"重", ja:"重い", es:"pesado", fr:"lourd", ru:"тяжёлый", pt:"pesado", ar:"ثقيل", hi:"भारी", it:"pesante"},
  "가볍다": {en:"to be light (weight)", zh:"轻", ja:"軽い", es:"ligero", fr:"léger", ru:"лёгкий", pt:"leve", ar:"خفيف", hi:"हल्का", it:"leggero"},
  "쉽다": {en:"to be easy", zh:"容易", ja:"易しい", es:"fácil", fr:"facile", ru:"лёгкий", pt:"fácil", ar:"سهل", hi:"आसान", it:"facile"},
  "어렵다": {en:"to be difficult", zh:"难", ja:"難しい", es:"difícil", fr:"difficile", ru:"трудный", pt:"difícil", ar:"صعب", hi:"कठिन", it:"difficile"},
  "깨끗하다": {en:"to be clean", zh:"干净", ja:"きれい", es:"limpio", fr:"propre", ru:"чистый", pt:"limpo", ar:"نظيف", hi:"साफ़", it:"pulito"},
  "더럽다": {en:"to be dirty", zh:"脏", ja:"汚い", es:"sucio", fr:"sale", ru:"грязный", pt:"sujo", ar:"متسخ", hi:"गंदा", it:"sporco"},
  "밝다": {en:"to be bright", zh:"亮", ja:"明るい", es:"brillante", fr:"clair", ru:"светлый", pt:"claro", ar:"مضيء", hi:"उज्ज्वल", it:"luminoso"},
  "어둡다": {en:"to be dark", zh:"暗", ja:"暗い", es:"oscuro", fr:"sombre", ru:"тёмный", pt:"escuro", ar:"مظلم", hi:"अँधेरा", it:"buio"},
  "뜨겁다": {en:"to be hot (to touch)", zh:"烫", ja:"熱い", es:"caliente", fr:"chaud", ru:"горячий", pt:"quente", ar:"ساخن", hi:"गरम", it:"caldo"},
  "차갑다": {en:"to be cold (to touch)", zh:"冰凉", ja:"冷たい", es:"frío", fr:"froid", ru:"холодный", pt:"frio", ar:"بارد", hi:"ठंडा", it:"freddo"},
  "달다": {en:"to be sweet", zh:"甜", ja:"甘い", es:"dulce", fr:"sucré", ru:"сладкий", pt:"doce", ar:"حلو", hi:"मीठा", it:"dolce"},
  "맵다": {en:"to be spicy", zh:"辣", ja:"辛い", es:"picante", fr:"épicé", ru:"острый", pt:"picante", ar:"حار", hi:"तीखा", it:"piccante"},
  "배고프다": {en:"to be hungry", zh:"饿", ja:"お腹がすく", es:"tener hambre", fr:"avoir faim", ru:"голодный", pt:"com fome", ar:"جائع", hi:"भूखा", it:"affamato"},
  "피곤하다": {en:"to be tired", zh:"累", ja:"疲れる", es:"cansado", fr:"fatigué", ru:"усталый", pt:"cansado", ar:"متعب", hi:"थका", it:"stanco"},
  "재미있다": {en:"to be fun / interesting", zh:"有趣", ja:"面白い", es:"divertido", fr:"amusant", ru:"интересный", pt:"divertido", ar:"ممتع", hi:"मज़ेदार", it:"divertente"},
  "멀다": {en:"to be far", zh:"远", ja:"遠い", es:"lejos", fr:"loin", ru:"далёкий", pt:"longe", ar:"بعيد", hi:"दूर", it:"lontano"},
  "가깝다": {en:"to be near", zh:"近", ja:"近い", es:"cerca", fr:"proche", ru:"близкий", pt:"perto", ar:"قريب", hi:"पास", it:"vicino"},
  "나쁘다": {en:"to be bad", zh:"坏", ja:"悪い", es:"malo", fr:"mauvais", ru:"плохой", pt:"ruim", ar:"سيئ", hi:"बुरा", it:"cattivo"},
  "아프다": {en:"to be sick / hurt", zh:"疼", ja:"痛い", es:"doler", fr:"avoir mal", ru:"болеть", pt:"doer", ar:"مريض", hi:"बीमार", it:"malato"},
  "같다": {en:"to be same", zh:"一样", ja:"同じ", es:"igual", fr:"pareil", ru:"одинаковый", pt:"igual", ar:"نفس", hi:"समान", it:"uguale"},
  "다르다": {en:"to be different", zh:"不同", ja:"違う", es:"diferente", fr:"différent", ru:"разный", pt:"diferente", ar:"مختلف", hi:"अलग", it:"diverso"},
  "새롭다": {en:"to be new", zh:"新", ja:"新しい", es:"nuevo", fr:"nouveau", ru:"новый", pt:"novo", ar:"جديد", hi:"नया", it:"nuovo"},

  // ── batch 4 (more common animals) ──
  "사자": {en:"lion", zh:"狮子", ja:"ライオン", es:"león", fr:"lion", ru:"лев", pt:"leão", ar:"أسد", hi:"शेर", it:"leone"},
  "호랑이": {en:"tiger", zh:"老虎", ja:"虎", es:"tigre", fr:"tigre", ru:"тигр", pt:"tigre", ar:"نمر", hi:"बाघ", it:"tigre"},
  "공룡": {en:"dinosaur", zh:"恐龙", ja:"恐竜", es:"dinosaurio", fr:"dinosaure", ru:"динозавр", pt:"dinossauro", ar:"ديناصور", hi:"डायनासोर", it:"dinosauro"},
  "문어": {en:"octopus", zh:"章鱼", ja:"タコ", es:"pulpo", fr:"pieuvre", ru:"осьминог", pt:"polvo", ar:"أخطبوط", hi:"ऑक्टोपस", it:"polpo"},
  "게": {en:"crab", zh:"螃蟹", ja:"カニ", es:"cangrejo", fr:"crabe", ru:"краб", pt:"caranguejo", ar:"سلطعون", hi:"केकड़ा", it:"granchio"},
  "펭귄": {en:"penguin", zh:"企鹅", ja:"ペンギン", es:"pingüino", fr:"pingouin", ru:"пингвин", pt:"pinguim", ar:"بطريق", hi:"पेंगुइन", it:"pinguino"},
  "악어": {en:"crocodile", zh:"鳄鱼", ja:"ワニ", es:"cocodrilo", fr:"crocodile", ru:"крокодил", pt:"crocodilo", ar:"تمساح", hi:"मगरमच्छ", it:"coccodrillo"},
  "다람쥐": {en:"squirrel", zh:"松鼠", ja:"リス", es:"ardilla", fr:"écureuil", ru:"белка", pt:"esquilo", ar:"سنجاب", hi:"गिलहरी", it:"scoiattolo"},
  "달팽이": {en:"snail", zh:"蜗牛", ja:"かたつむり", es:"caracol", fr:"escargot", ru:"улитка", pt:"caracol", ar:"حلزون", hi:"घोंघा", it:"lumaca"},
  "지렁이": {en:"earthworm", zh:"蚯蚓", ja:"ミミズ", es:"lombriz", fr:"ver de terre", ru:"дождевой червь", pt:"minhoca", ar:"دودة الأرض", hi:"केंचुआ", it:"lombrico"}
};



